-- Migration 0006: Auto-generated title flag (quick-start, ADR 0029)
-- Marks a Meeting whose title is a placeholder generated by the "Direct
-- starten" quick-start path. The final pass may replace such a title with an
-- inferred one and then clear the flag; a user edit of the title also clears it.
-- INTEGER NOT NULL DEFAULT 0 (false) so every existing row keeps its real,
-- user-set title and is never overwritten — no backfill needed.

ALTER TABLE meetings ADD COLUMN title_auto_generated INTEGER NOT NULL DEFAULT 0;
