/**
 * Meeting-prep IPC contract (barrel-composed — see ../ipc.ts).
 *
 * Invoke channels: meeting:create, agendaItem:add, agendaItem:remove,
 * agendaItem:confirm, agendaItem:editAndConfirm, participant:add,
 * participant:remove. Push event: agenda:changed.
 */

import { z } from 'zod'

import { MeetingSchema, AgendaItemSchema, ParticipantSchema } from '../domain'

import type { IpcChannelSchema, UnsubscribeFn } from './common'

// ---------------------------------------------------------------------------
// meeting:create — create a new meeting in draft state (item 0014)
// ---------------------------------------------------------------------------

export const MeetingCreateRequestSchema = z.object({
  title: z.string().min(1, 'Meeting title cannot be empty'),
  primaryLanguage: z.string().min(1, 'Primary language cannot be empty'),
  /**
   * Whether `title` is an auto-generated placeholder (the "Direct starten"
   * quick-start path). Defaults to false for a normal user-set title. ADR 0029.
   */
  titleAutoGenerated: z.boolean().default(false),
})

export const MeetingCreateResponseSchema = MeetingSchema

export type MeetingCreateRequest = z.infer<typeof MeetingCreateRequestSchema>
export type MeetingCreateResponse = z.infer<typeof MeetingCreateResponseSchema>

// ---------------------------------------------------------------------------
// agendaItem:add — add an agenda item to a meeting (item 0014)
// ---------------------------------------------------------------------------

export const AgendaItemAddRequestSchema = z.object({
  meetingId: z.string().min(1, 'Meeting ID cannot be empty'),
  title: z.string().min(1, 'Agenda item title cannot be empty'),
  topic: z.string().min(1, 'Agenda item topic cannot be empty'),
})

export const AgendaItemAddResponseSchema = AgendaItemSchema

export type AgendaItemAddRequest = z.infer<typeof AgendaItemAddRequestSchema>
export type AgendaItemAddResponse = z.infer<typeof AgendaItemAddResponseSchema>

// ---------------------------------------------------------------------------
// agendaItem:remove — remove an agenda item (item 0014)
// ---------------------------------------------------------------------------

export const AgendaItemRemoveRequestSchema = z.object({
  agendaItemId: z.string().min(1, 'Agenda item ID cannot be empty'),
})

export const AgendaItemRemoveResponseSchema = z.object({ ok: z.literal(true) })

export type AgendaItemRemoveRequest = z.infer<typeof AgendaItemRemoveRequestSchema>
export type AgendaItemRemoveResponse = z.infer<typeof AgendaItemRemoveResponseSchema>

// ---------------------------------------------------------------------------
// participant:add — add a participant to a meeting (item 0014)
// ---------------------------------------------------------------------------

export const ParticipantAddRequestSchema = z.object({
  meetingId: z.string().min(1, 'Meeting ID cannot be empty'),
  name: z.string().min(1, 'Participant name cannot be empty'),
})

export const ParticipantAddResponseSchema = ParticipantSchema

export type ParticipantAddRequest = z.infer<typeof ParticipantAddRequestSchema>
export type ParticipantAddResponse = z.infer<typeof ParticipantAddResponseSchema>

// ---------------------------------------------------------------------------
// participant:remove — remove a participant (item 0014)
// ---------------------------------------------------------------------------

export const ParticipantRemoveRequestSchema = z.object({
  participantId: z.string().min(1, 'Participant ID cannot be empty'),
})

export const ParticipantRemoveResponseSchema = z.object({ ok: z.literal(true) })

export type ParticipantRemoveRequest = z.infer<typeof ParticipantRemoveRequestSchema>
export type ParticipantRemoveResponse = z.infer<typeof ParticipantRemoveResponseSchema>

// ---------------------------------------------------------------------------
// agenda:changed — main → renderer push event (live agenda inference, ADR 0029)
//
// Emitted whenever the live agenda set changes (the slow agenda scheduler
// proposes new items). Carries the full current agenda (Confirmed + Proposed)
// so the renderer replaces its local agenda state, exactly like nudges:changed.
// ---------------------------------------------------------------------------

export const AgendaChangedPayloadSchema = z.object({
  agendaItems: z.array(AgendaItemSchema),
})

export type AgendaChangedPayload = z.infer<typeof AgendaChangedPayloadSchema>

// ---------------------------------------------------------------------------
// agendaItem:confirm — note-taker confirms a Proposed Agenda Item (ADR 0029)
//
// Persists state → 'confirmed' so the item becomes a live routing bucket
// immediately. Returns the updated item.
// ---------------------------------------------------------------------------

export const AgendaItemConfirmRequestSchema = z.object({
  agendaItemId: z.string().min(1, 'Agenda item ID cannot be empty'),
})

export const AgendaItemConfirmResponseSchema = AgendaItemSchema

export type AgendaItemConfirmRequest = z.infer<typeof AgendaItemConfirmRequestSchema>
export type AgendaItemConfirmResponse = z.infer<typeof AgendaItemConfirmResponseSchema>

// ---------------------------------------------------------------------------
// agendaItem:editAndConfirm — edit a Proposed Agenda Item's title/topic and
// confirm it in one step (ADR 0029)
// ---------------------------------------------------------------------------

export const AgendaItemEditAndConfirmRequestSchema = z.object({
  agendaItemId: z.string().min(1, 'Agenda item ID cannot be empty'),
  title: z.string().min(1, 'Agenda item title cannot be empty'),
  topic: z.string().min(1, 'Agenda item topic cannot be empty'),
})

export const AgendaItemEditAndConfirmResponseSchema = AgendaItemSchema

export type AgendaItemEditAndConfirmRequest = z.infer<typeof AgendaItemEditAndConfirmRequestSchema>
export type AgendaItemEditAndConfirmResponse = z.infer<
  typeof AgendaItemEditAndConfirmResponseSchema
>

// ---------------------------------------------------------------------------
// Channel fragment + schema slice + API fragment
// ---------------------------------------------------------------------------

export type PrepChannel =
  | 'meeting:create'
  | 'agendaItem:add'
  | 'agendaItem:remove'
  | 'agendaItem:confirm'
  | 'agendaItem:editAndConfirm'
  | 'participant:add'
  | 'participant:remove'

export const prepChannelSchemas = {
  'meeting:create': { request: MeetingCreateRequestSchema, response: MeetingCreateResponseSchema },
  'agendaItem:add': { request: AgendaItemAddRequestSchema, response: AgendaItemAddResponseSchema },
  'agendaItem:remove': {
    request: AgendaItemRemoveRequestSchema,
    response: AgendaItemRemoveResponseSchema,
  },
  'agendaItem:confirm': {
    request: AgendaItemConfirmRequestSchema,
    response: AgendaItemConfirmResponseSchema,
  },
  'agendaItem:editAndConfirm': {
    request: AgendaItemEditAndConfirmRequestSchema,
    response: AgendaItemEditAndConfirmResponseSchema,
  },
  'participant:add': {
    request: ParticipantAddRequestSchema,
    response: ParticipantAddResponseSchema,
  },
  'participant:remove': {
    request: ParticipantRemoveRequestSchema,
    response: ParticipantRemoveResponseSchema,
  },
} satisfies Record<PrepChannel, IpcChannelSchema>

export interface PrepApi {
  /** Create a new meeting in draft state. */
  meetingCreate: (req: MeetingCreateRequest) => Promise<MeetingCreateResponse>
  /** Add an agenda item to a meeting. */
  agendaItemAdd: (req: AgendaItemAddRequest) => Promise<AgendaItemAddResponse>
  /** Remove an agenda item. */
  agendaItemRemove: (req: AgendaItemRemoveRequest) => Promise<AgendaItemRemoveResponse>
  /** Add a participant to a meeting. */
  participantAdd: (req: ParticipantAddRequest) => Promise<ParticipantAddResponse>
  /** Remove a participant. */
  participantRemove: (req: ParticipantRemoveRequest) => Promise<ParticipantRemoveResponse>
  /**
   * Subscribe to live agenda updates pushed from main (ADR 0029). Fired when the
   * slow agenda scheduler proposes new items. The callback receives the full
   * current agenda; the UI replaces its local agenda state. Returns an
   * unsubscribe function.
   */
  onAgendaChanged: (cb: (payload: AgendaChangedPayload) => void) => UnsubscribeFn
  /**
   * Confirm a Proposed Agenda Item (ADR 0029). Persists state → 'confirmed' so
   * it becomes a live routing bucket immediately. Returns the updated item.
   */
  agendaItemConfirm: (req: AgendaItemConfirmRequest) => Promise<AgendaItemConfirmResponse>
  /**
   * Edit a Proposed Agenda Item's title/topic and confirm it in one step
   * (ADR 0029).
   */
  agendaItemEditAndConfirm: (
    req: AgendaItemEditAndConfirmRequest,
  ) => Promise<AgendaItemEditAndConfirmResponse>
}
