/**
 * @vitest-environment node
 *
 * Tests for AgendaProposalService (ADR 0029 — live agenda inference).
 *
 * The service inserts agent-proposed Agenda Items as `proposed`, skipping
 * near-duplicates of existing items (normalised-title compare). It never
 * touches Confirmed items and never revises/retracts its own — append-only.
 */
import Database from 'better-sqlite3'
import { describe, it, expect, beforeEach } from 'vitest'

import type { Meeting } from '@shared/domain'
import { OffAgenda } from '@shared/domain'

import { runMigrations } from '../db/migrate'
import { agendaItemRepo } from '../db/repos/agendaItemRepo'
import { meetingRepo } from '../db/repos/meetingRepo'

import { AgendaProposalService } from './agendaProposalService'

const MTG = 'mtg-prop'

const MEETING: Meeting = {
  id: MTG,
  title: 'Test',
  state: 'live',
  source: 'live',
  paused: false,
  createdAt: '2026-06-25T10:00:00.000Z',
  primaryLanguage: 'nl',
  titleAutoGenerated: false,
}

function openDb(): Database.Database {
  const db = new Database(':memory:')
  db.pragma('foreign_keys = ON')
  runMigrations(db)
  meetingRepo(db).insert(MEETING)
  return db
}

describe('AgendaProposalService', () => {
  let db: Database.Database
  let repo: ReturnType<typeof agendaItemRepo>
  let service: AgendaProposalService

  beforeEach(() => {
    db = openDb()
    repo = agendaItemRepo(db)
    service = new AgendaProposalService({ agendaItemRepo: repo })
  })

  it('inserts proposed agenda items for new topics', () => {
    const proposed = service.propose(MTG, [
      { title: 'Begroting', topic: 'Q3-begroting' },
      { title: 'Planning', topic: 'Volgend kwartaal' },
    ])

    expect(proposed).toHaveLength(2)
    const stored = repo.listByMeeting(MTG)
    expect(stored.map((a) => a.title).sort()).toEqual(['Begroting', 'Planning'])
    expect(stored.every((a) => a.state === 'proposed')).toBe(true)
  })

  it('skips a topic that matches an existing Confirmed item (normalised)', () => {
    repo.insert(
      { id: 'ai-confirmed', title: 'Begroting', topic: 'Bestaand', state: 'confirmed' },
      MTG,
    )

    const proposed = service.propose(MTG, [{ title: '  begroting ', topic: 'Q3' }])

    expect(proposed).toHaveLength(0)
    expect(repo.listByMeeting(MTG)).toHaveLength(1) // only the original confirmed item
  })

  it('skips a topic that matches an already-proposed item', () => {
    repo.insert({ id: 'ai-prop', title: 'Begroting', topic: 'Eerder', state: 'proposed' }, MTG)

    const proposed = service.propose(MTG, [{ title: 'Begroting', topic: 'Opnieuw' }])

    expect(proposed).toHaveLength(0)
    expect(repo.listByMeeting(MTG)).toHaveLength(1)
  })

  it('dedups within a single batch', () => {
    const proposed = service.propose(MTG, [
      { title: 'Begroting', topic: 'Q3' },
      { title: 'begroting', topic: 'duplicaat' },
    ])

    expect(proposed).toHaveLength(1)
    expect(repo.listByMeeting(MTG)).toHaveLength(1)
  })

  it('ignores the Off-agenda sentinel', () => {
    const proposed = service.propose(MTG, [{ title: OffAgenda.title, topic: 'iets' }])

    expect(proposed).toHaveLength(0)
    expect(repo.listByMeeting(MTG)).toHaveLength(0)
  })
})
