/**
 * @vitest-environment node
 *
 * Tests for AgendaInferenceScheduler (ADR 0029 — live agenda inference).
 *
 * Deterministic: FakeClock + FakeExtractionProvider + in-memory DB. The
 * scheduler runs a slow cadence; on each tick past the boundary it infers
 * agenda topics over the whole transcript, grounded by the current agenda, and
 * feeds them to the AgendaProposalService.
 */
import Database from 'better-sqlite3'
import { describe, it, expect, beforeEach } from 'vitest'

import type { Meeting } from '@shared/domain'
import { FakeClock, FakeExtractionProvider } from '@shared/providers'

import { runMigrations } from '../db/migrate'
import { agendaItemRepo } from '../db/repos/agendaItemRepo'
import { meetingRepo } from '../db/repos/meetingRepo'
import { transcriptSpanRepo } from '../db/repos/transcriptSpanRepo'

import { AgendaInferenceScheduler } from './agendaInferenceScheduler'
import { AgendaProposalService } from './agendaProposalService'

const MTG = 'mtg-agenda-sched'
const CADENCE = 90_000

const MEETING: Meeting = {
  id: MTG,
  title: 'Test',
  state: 'live',
  source: 'live',
  paused: false,
  createdAt: '2026-06-25T10:00:00.000Z',
  primaryLanguage: 'nl',
  titleAutoGenerated: false,
}

interface Harness {
  db: Database.Database
  clock: FakeClock
  provider: FakeExtractionProvider
  spanRepo: ReturnType<typeof transcriptSpanRepo>
  aiRepo: ReturnType<typeof agendaItemRepo>
  scheduler: AgendaInferenceScheduler
}

function build(): Harness {
  const db = new Database(':memory:')
  db.pragma('foreign_keys = ON')
  runMigrations(db)
  meetingRepo(db).insert(MEETING)

  const clock = new FakeClock(0)
  const provider = new FakeExtractionProvider()
  const spanRepo = transcriptSpanRepo(db)
  const aiRepo = agendaItemRepo(db)
  const proposalService = new AgendaProposalService({ agendaItemRepo: aiRepo })

  const scheduler = new AgendaInferenceScheduler({
    provider,
    proposalService,
    spanRepo,
    agendaItemRepo: aiRepo,
    clock,
    cadenceMs: CADENCE,
  })

  return { db, clock, provider, spanRepo, aiRepo, scheduler }
}

function seedSpan(h: Harness, id: string): void {
  h.spanRepo.insert({ id, text: `Tekst ${id}`, startMs: 0, endMs: 1000 }, MTG)
}

describe('AgendaInferenceScheduler', () => {
  let h: Harness

  beforeEach(() => {
    h = build()
  })

  it('does not fire before the slow cadence boundary', async () => {
    seedSpan(h, 's1')
    h.clock.tick(CADENCE - 1)
    await h.scheduler.tick(MTG)
    expect(h.provider.inferContextCalls()).toHaveLength(0)
  })

  it('fires once the cadence boundary is crossed and proposes inferred topics', async () => {
    seedSpan(h, 's1')
    h.provider.scriptInferContextResponse({
      agendaItems: [{ title: 'Begroting', topic: 'Q3-begroting' }],
      participants: [],
    })

    h.clock.tick(CADENCE)
    await h.scheduler.tick(MTG)

    expect(h.provider.inferContextCalls()).toHaveLength(1)
    const agenda = h.aiRepo.listByMeeting(MTG)
    expect(agenda.map((a) => a.title)).toContain('Begroting')
    expect(agenda.find((a) => a.title === 'Begroting')?.state).toBe('proposed')
  })

  it('passes the current agenda as grounding (knownAgendaItems)', async () => {
    h.aiRepo.insert(
      { id: 'ai-1', title: 'Bestaand punt', topic: 'reeds geagendeerd', state: 'confirmed' },
      MTG,
    )
    seedSpan(h, 's1')

    h.clock.tick(CADENCE)
    await h.scheduler.tick(MTG)

    const call = h.provider.inferContextCalls()[0]
    expect(call?.knownAgendaItems?.map((a) => a.title)).toContain('Bestaand punt')
  })

  it('does not fire while paused, and resumes after', async () => {
    seedSpan(h, 's1')
    h.scheduler.pause()

    h.clock.tick(CADENCE)
    await h.scheduler.tick(MTG)
    expect(h.provider.inferContextCalls()).toHaveLength(0)

    h.scheduler.resume()
    h.clock.tick(CADENCE)
    await h.scheduler.tick(MTG)
    expect(h.provider.inferContextCalls()).toHaveLength(1)
  })

  it('is a no-op when there are no spans yet', async () => {
    h.clock.tick(CADENCE)
    await h.scheduler.tick(MTG)
    expect(h.provider.inferContextCalls()).toHaveLength(0)
  })
})
