/**
 * @vitest-environment node
 *
 * Tests for ExtractionSession — the shared extraction core (audit A3).
 *
 * The core owns the scheduler + item service + emit-plumbing. These tests drive
 * it directly (no LiveExtractionRuntime, no session controller) to prove:
 *   - a rolling tick proposes items and emits items:changed + nudges:changed
 *   - runFinalPass persists summaries and emits items:summaries + nudges:changed
 *   - agenda:changed is emitted on end ONLY when an agendaItemRepo is wired
 *     (live) and skipped when absent (import)
 *   - the injected getContext() is read at emit time
 *
 * Deterministic: FakeClock + FakeExtractionProvider + in-memory DB. (Principle #11.)
 */

import Database from 'better-sqlite3'
import { describe, expect, it } from 'vitest'

import type { AgendaItem, Meeting, MeetingId, Participant } from '@shared/domain'
import type { ItemsChangedPayload, ItemsSummariesPayload } from '@shared/ipc'
import { FakeClock, FakeExtractionProvider } from '@shared/providers'

import { runMigrations } from '../db/migrate'
import { actionRepo } from '../db/repos/actionRepo'
import { agendaItemRepo } from '../db/repos/agendaItemRepo'
import { decisionRepo } from '../db/repos/decisionRepo'
import { discussionSummaryRepo } from '../db/repos/discussionSummaryRepo'
import { meetingRepo } from '../db/repos/meetingRepo'
import { transcriptSpanRepo } from '../db/repos/transcriptSpanRepo'

import type { MeetingContext } from './extractionLoopScheduler'
import { ExtractionSession } from './extractionSession'

// ---------------------------------------------------------------------------
// Harness
// ---------------------------------------------------------------------------

interface RecordedSend {
  channel: string
  payload: unknown
}

class FakeIpcSender {
  readonly sent: RecordedSend[] = []
  send(channel: string, payload: unknown): void {
    this.sent.push({ channel, payload })
  }
  sentOn(channel: string): unknown[] {
    return this.sent.filter((s) => s.channel === channel).map((s) => s.payload)
  }
}

const MTG_ID: MeetingId = 'mtg-core-test'

const MEETING: Meeting = {
  id: MTG_ID,
  title: 'Core test',
  state: 'live',
  source: 'live',
  paused: false,
  createdAt: '2026-06-18T09:00:00.000Z',
  primaryLanguage: 'nl',
  titleAutoGenerated: false,
}

const AGENDA: AgendaItem[] = [
  { id: 'ai-1', title: 'Q3 review', topic: 'Review Q3 results', state: 'confirmed' },
]
const PARTICIPANTS: Participant[] = [{ id: 'p-1', name: 'Jeroen' }]
const CONTEXT: MeetingContext = {
  agendaItems: AGENDA,
  participants: PARTICIPANTS,
  primaryLanguage: 'nl',
}

function openDb(): Database.Database {
  const db = new Database(':memory:')
  db.pragma('foreign_keys = ON')
  runMigrations(db)
  return db
}

function buildCore(opts: { withAgendaRepo?: boolean; getContext?: () => MeetingContext } = {}) {
  const db = openDb()
  meetingRepo(db).insert(MEETING)
  const clock = new FakeClock(0)
  const provider = new FakeExtractionProvider()
  const dRepo = decisionRepo(db)
  const aRepo = actionRepo(db)
  const dsRepo = discussionSummaryRepo(db)
  const spanRepo = transcriptSpanRepo(db)
  const aiRepo = agendaItemRepo(db)
  const sender = new FakeIpcSender()

  const core = new ExtractionSession({
    meetingId: MTG_ID,
    sender,
    provider,
    clock,
    cadenceMs: 20_000,
    decisionsRepo: dRepo,
    actionsRepo: aRepo,
    spanRepo,
    dsRepo,
    getContext: opts.getContext ?? (() => CONTEXT),
    ...(opts.withAgendaRepo === true ? { agendaItemRepo: aiRepo } : {}),
  })

  return { db, clock, provider, dRepo, aRepo, dsRepo, spanRepo, aiRepo, sender, core }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('ExtractionSession — rolling tick', () => {
  it('proposes items and emits items:changed + nudges:changed', async () => {
    const { clock, provider, sender, core } = buildCore()
    provider.scriptRollingResponse({
      proposedDecisions: [{ rationale: 'Ship it', sourceSpanId: 's1', agendaItemHint: 'ai-1' }],
      proposedActions: [],
    })

    core.addSpan({ id: 's1', text: 'We ship in Q3', startMs: 0, endMs: 1000 }, MTG_ID)
    clock.tick(20_000)
    await core.tick(CONTEXT)

    const changed = sender.sentOn('items:changed') as ItemsChangedPayload[]
    expect(changed.length).toBeGreaterThan(0)
    expect(changed[changed.length - 1]?.decisions.length).toBe(1)
    expect(sender.sentOn('nudges:changed').length).toBeGreaterThan(0)
  })

  it('does not fire a turn before the cadence boundary', async () => {
    const { provider, sender, core } = buildCore()
    core.addSpan({ id: 's1', text: 'hi', startMs: 0, endMs: 1000 }, MTG_ID)
    await core.tick(CONTEXT)
    expect(provider.callCount()).toBe(0)
    expect(sender.sentOn('items:changed')).toHaveLength(0)
  })
})

describe('ExtractionSession — final pass', () => {
  it('persists summaries and emits items:summaries + nudges:changed', async () => {
    const { provider, dsRepo, sender, core } = buildCore()
    provider.scriptFinalPassResponse({
      proposedDecisions: [],
      proposedActions: [],
      discussionSummaries: [{ agendaItemHint: 'ai-1', text: 'Besproken: Q3.' }],
    })

    await core.runFinalPass(MEETING, CONTEXT)

    expect(dsRepo.listByMeeting(MTG_ID).length).toBeGreaterThan(0)
    const summaryEvents = sender.sentOn('items:summaries') as ItemsSummariesPayload[]
    expect(summaryEvents).toHaveLength(1)
    expect(summaryEvents[0]?.summaries.length).toBeGreaterThan(0)
    expect(sender.sentOn('nudges:changed').length).toBeGreaterThan(0)
  })

  it('emits agenda:changed on end when an agendaItemRepo is wired (live)', async () => {
    const { provider, sender, core } = buildCore({ withAgendaRepo: true })
    provider.scriptFinalPassResponse({ proposedDecisions: [], proposedActions: [] })

    await core.runFinalPass(MEETING, CONTEXT)

    expect(sender.sentOn('agenda:changed')).toHaveLength(1)
  })

  it('does NOT emit agenda:changed when no agendaItemRepo is wired (import)', async () => {
    const { provider, sender, core } = buildCore({ withAgendaRepo: false })
    provider.scriptFinalPassResponse({ proposedDecisions: [], proposedActions: [] })

    await core.runFinalPass(MEETING, CONTEXT)

    expect(sender.sentOn('agenda:changed')).toHaveLength(0)
  })

  it('reads getContext() at emit time so nudges reflect the current context', async () => {
    // Start with an empty agenda; enrich the context the getter returns before
    // the final pass. The nudge derivation must see the enriched agenda.
    let ctx: MeetingContext = { agendaItems: [], participants: [], primaryLanguage: 'nl' }
    const { provider, sender, core } = buildCore({ getContext: () => ctx })
    provider.scriptFinalPassResponse({ proposedDecisions: [], proposedActions: [] })

    ctx = CONTEXT // enrich after construction, before the pass
    await core.runFinalPass(MEETING, CONTEXT)

    // A nudges:changed event was emitted (the getter was consulted, no throw).
    expect(sender.sentOn('nudges:changed').length).toBeGreaterThan(0)
  })
})
