/**
 * @vitest-environment node
 *
 * Tests for persistInferredContext — the "inferred agenda/participants are
 * persisted as Proposed" rule (ADR 0029) that used to be duplicated in
 * liveExtractionRuntime._inferContextOnEnd and
 * ImportSessionController._inferAndPersistContext (review item 5).
 */
import Database from 'better-sqlite3'
import { describe, it, expect, beforeEach } from 'vitest'

import type { MeetingId } from '@shared/domain'

import { runMigrations } from '../db/migrate'
import { agendaItemRepo } from '../db/repos/agendaItemRepo'
import { meetingRepo } from '../db/repos/meetingRepo'
import { participantRepo } from '../db/repos/participantRepo'

import { persistInferredContext } from './inferredContextPersistence'

const MEETING_ID: MeetingId = 'mtg-1'

function openDb(): Database.Database {
  const db = new Database(':memory:')
  db.pragma('foreign_keys = ON')
  runMigrations(db)
  meetingRepo(db).insert({
    id: MEETING_ID,
    title: 'Test',
    state: 'live',
    source: 'live',
    paused: false,
    createdAt: '2026-07-04T10:00:00.000Z',
    primaryLanguage: 'nl',
    titleAutoGenerated: false,
  })
  return db
}

describe('persistInferredContext', () => {
  let db: Database.Database

  beforeEach(() => {
    db = openDb()
  })

  it('persists inferred agenda items as Proposed with fresh ids, and returns them', () => {
    const aRepo = agendaItemRepo(db)
    const pRepo = participantRepo(db)

    const result = persistInferredContext(
      { agendaItemRepo: aRepo, participantRepo: pRepo },
      MEETING_ID,
      {
        agendaItems: [{ title: 'Begroting', topic: 'Q3' }],
        participants: [{ name: 'Alice' }],
      },
    )

    expect(result.agendaItems).toHaveLength(1)
    expect(result.agendaItems[0]?.state).toBe('proposed')
    expect(result.agendaItems[0]?.id).toMatch(/[0-9a-f-]{36}/)
    expect(result.participants.map((p) => p.name)).toEqual(['Alice'])

    // Persisted to the DB under the meeting.
    const persistedAgenda = aRepo.listByMeeting(MEETING_ID)
    expect(persistedAgenda.map((a) => a.title)).toEqual(['Begroting'])
    expect(persistedAgenda[0]?.state).toBe('proposed')
    expect(pRepo.listByMeeting(MEETING_ID).map((p) => p.name)).toEqual(['Alice'])
  })

  it('persists nothing and returns empty collections for an empty inference', () => {
    const aRepo = agendaItemRepo(db)
    const pRepo = participantRepo(db)

    const result = persistInferredContext(
      { agendaItemRepo: aRepo, participantRepo: pRepo },
      MEETING_ID,
      { agendaItems: [], participants: [] },
    )

    expect(result.agendaItems).toHaveLength(0)
    expect(result.participants).toHaveLength(0)
    expect(aRepo.listByMeeting(MEETING_ID)).toHaveLength(0)
    expect(pRepo.listByMeeting(MEETING_ID)).toHaveLength(0)
  })
})
