/**
 * @vitest-environment node
 *
 * Tests for sendItemsChanged — the single authoritative items:changed emitter.
 */
import Database from 'better-sqlite3'
import { describe, it, expect, beforeEach } from 'vitest'

import type { MeetingId } from '@shared/domain'
import type { ItemsChangedPayload } from '@shared/ipc'

import { runMigrations } from '../db/migrate'
import { actionRepo } from '../db/repos/actionRepo'
import { decisionRepo } from '../db/repos/decisionRepo'
import { meetingRepo } from '../db/repos/meetingRepo'
import { transcriptSpanRepo } from '../db/repos/transcriptSpanRepo'

import { sendItemsChanged } from './itemsChangedNotifier'

const MEETING_ID: MeetingId = 'mtg-1'
const SPAN_ID = 'span-1'
const AGENDA_ID = 'ai-1'

function openDb(): Database.Database {
  const db = new Database(':memory:')
  db.pragma('foreign_keys = ON')
  runMigrations(db)
  meetingRepo(db).insert({
    id: MEETING_ID,
    title: 'Test',
    state: 'live',
    source: 'live',
    paused: false,
    createdAt: '2026-07-04T10:00:00.000Z',
    primaryLanguage: 'nl',
    titleAutoGenerated: false,
  })
  transcriptSpanRepo(db).insert({ id: SPAN_ID, text: 'x', startMs: 0, endMs: 1 }, MEETING_ID)
  return db
}

describe('sendItemsChanged', () => {
  let db: Database.Database
  let sent: { channel: string; payload: ItemsChangedPayload }[]
  const sender = {
    send: (channel: string, payload: unknown) =>
      sent.push({ channel, payload: payload as ItemsChangedPayload }),
  }

  beforeEach(() => {
    db = openDb()
    sent = []
  })

  it('emits the full current item set (both states) for the meeting, with the meetingId', () => {
    const dRepo = decisionRepo(db)
    const aRepo = actionRepo(db)
    dRepo.insert(
      {
        id: 'd-1',
        rationale: 'proposed one',
        agendaItemId: AGENDA_ID,
        sourceSpanId: SPAN_ID,
        state: 'proposed',
      },
      MEETING_ID,
    )
    dRepo.insert(
      {
        id: 'd-2',
        rationale: 'confirmed one',
        agendaItemId: AGENDA_ID,
        sourceSpanId: SPAN_ID,
        state: 'confirmed',
      },
      MEETING_ID,
    )
    aRepo.insert(
      {
        id: 'a-1',
        agendaItemId: AGENDA_ID,
        sourceSpanId: SPAN_ID,
        status: 'open',
        state: 'proposed',
      },
      MEETING_ID,
    )

    sendItemsChanged(sender, MEETING_ID, dRepo, aRepo)

    expect(sent).toHaveLength(1)
    expect(sent[0]?.channel).toBe('items:changed')
    const payload = sent[0]?.payload
    expect(payload?.meetingId).toBe(MEETING_ID)
    expect(payload?.decisions.map((d) => d.id).sort()).toEqual(['d-1', 'd-2'])
    expect(payload?.actions.map((a) => a.id)).toEqual(['a-1'])
  })
})
