/**
 * @vitest-environment node
 *
 * Tests for MeetingContextOwner — the single owner of a live meeting's
 * MeetingContext (review item 5b). It replaces the scattered seed / mutate /
 * derive of the context that used to live inline in LiveExtractionRuntime
 * (`_context` + `_liveRoutingContext`).
 */
import Database from 'better-sqlite3'
import { describe, it, expect, beforeEach } from 'vitest'

import type { AgendaItem, MeetingId, Participant } from '@shared/domain'

import { runMigrations } from '../db/migrate'
import { agendaItemRepo } from '../db/repos/agendaItemRepo'
import { meetingRepo } from '../db/repos/meetingRepo'

import { MeetingContextOwner } from './meetingContextOwner'

const MEETING_ID: MeetingId = 'mtg-1'

function openDb(): Database.Database {
  const db = new Database(':memory:')
  db.pragma('foreign_keys = ON')
  runMigrations(db)
  meetingRepo(db).insert({
    id: MEETING_ID,
    title: 'Test',
    state: 'live',
    source: 'live',
    paused: false,
    createdAt: '2026-07-04T10:00:00.000Z',
    primaryLanguage: 'nl',
    titleAutoGenerated: false,
  })
  return db
}

const AGENDA_CONFIRMED: AgendaItem = {
  id: 'ai-confirmed',
  title: 'Begroting',
  topic: 'Q3',
  state: 'confirmed',
}
const AGENDA_PROPOSED: AgendaItem = {
  id: 'ai-proposed',
  title: 'Rondvraag',
  topic: 'overig',
  state: 'proposed',
}

const SEED = {
  agendaItems: [] as AgendaItem[],
  participants: [] as Participant[],
  primaryLanguage: 'nl',
}

describe('MeetingContextOwner', () => {
  let db: Database.Database
  let aRepo: ReturnType<typeof agendaItemRepo>

  beforeEach(() => {
    db = openDb()
    aRepo = agendaItemRepo(db)
  })

  it('current() returns the seeded context', () => {
    const owner = new MeetingContextOwner(
      { agendaItems: [AGENDA_CONFIRMED], participants: [], primaryLanguage: 'en' },
      MEETING_ID,
      aRepo,
    )
    expect(owner.current().primaryLanguage).toBe('en')
    expect(owner.current().agendaItems.map((a) => a.id)).toEqual(['ai-confirmed'])
  })

  it('routingContext() returns only Confirmed agenda items from the repo (ADR 0029)', () => {
    aRepo.insert(AGENDA_CONFIRMED, MEETING_ID)
    aRepo.insert(AGENDA_PROPOSED, MEETING_ID)
    const owner = new MeetingContextOwner(SEED, MEETING_ID, aRepo)

    const routing = owner.routingContext()
    expect(routing.agendaItems.map((a) => a.id)).toEqual(['ai-confirmed'])
    expect(routing.primaryLanguage).toBe('nl')
  })

  it('routingContext() falls back to the static context when no agenda repo is wired', () => {
    const owner = new MeetingContextOwner(
      { agendaItems: [AGENDA_PROPOSED], participants: [], primaryLanguage: 'nl' },
      MEETING_ID,
      undefined,
    )
    // No repo: return the static context unchanged (Proposed item included).
    expect(owner.routingContext().agendaItems.map((a) => a.id)).toEqual(['ai-proposed'])
  })

  it('enrich() replaces agenda + participants but keeps primaryLanguage', () => {
    const owner = new MeetingContextOwner(SEED, MEETING_ID, aRepo)

    owner.enrich({
      agendaItems: [AGENDA_PROPOSED],
      participants: [{ id: 'p-1', name: 'Alice' }],
    })

    expect(owner.current().agendaItems.map((a) => a.id)).toEqual(['ai-proposed'])
    expect(owner.current().participants.map((p) => p.name)).toEqual(['Alice'])
    expect(owner.current().primaryLanguage).toBe('nl')
  })
})
