/**
 * @vitest-environment node
 *
 * Tests for MeetingQueryService — the read-only meeting-history queries that
 * used to live as pass-through closures inside registerIpcHandlers (item 6a of
 * the 2026-07 architecture review). Extracting them gives the "list / load /
 * delete / transcript" behaviour a real unit-test surface, away from Electron.
 */
import Database from 'better-sqlite3'
import { describe, it, expect, beforeEach } from 'vitest'

import type { MeetingId } from '@shared/domain'

import { runMigrations } from '../db/migrate'
import { actionRepo } from '../db/repos/actionRepo'
import { agendaItemRepo } from '../db/repos/agendaItemRepo'
import { decisionRepo } from '../db/repos/decisionRepo'
import { discussionSummaryRepo } from '../db/repos/discussionSummaryRepo'
import { meetingRepo } from '../db/repos/meetingRepo'
import { participantRepo } from '../db/repos/participantRepo'
import { transcriptSpanRepo } from '../db/repos/transcriptSpanRepo'

import { MeetingQueryService } from './meetingQueryService'

const ENDED: MeetingId = 'mtg-ended'
const DRAFT: MeetingId = 'mtg-draft'

function build(db: Database.Database): MeetingQueryService {
  return new MeetingQueryService({
    meetingRepo: meetingRepo(db),
    decisionRepo: decisionRepo(db),
    actionRepo: actionRepo(db),
    agendaItemRepo: agendaItemRepo(db),
    participantRepo: participantRepo(db),
    discussionSummaryRepo: discussionSummaryRepo(db),
    transcriptSpanRepo: transcriptSpanRepo(db),
  })
}

function openDb(): Database.Database {
  const db = new Database(':memory:')
  db.pragma('foreign_keys = ON')
  runMigrations(db)
  return db
}

function seedEndedMeeting(db: Database.Database): void {
  meetingRepo(db).insert({
    id: ENDED,
    title: 'Roadmap',
    state: 'ended',
    source: 'live',
    paused: false,
    createdAt: '2026-07-04T10:00:00.000Z',
    primaryLanguage: 'nl',
    titleAutoGenerated: false,
  })
  transcriptSpanRepo(db).insert(
    { id: 'span-1', text: 'Hallo allemaal', startMs: 0, endMs: 1000, speakerLabel: 'Speaker 0' },
    ENDED,
  )
  transcriptSpanRepo(db).insert(
    { id: 'span-2', text: 'We beginnen', startMs: 1000, endMs: 2000 },
    ENDED,
  )
  agendaItemRepo(db).insert(
    { id: 'ai-1', title: 'Begroting', topic: 'Q3', state: 'confirmed' },
    ENDED,
  )
  participantRepo(db).insert({ id: 'p-1', name: 'Alice' }, ENDED)
  decisionRepo(db).insert(
    {
      id: 'd-1',
      rationale: 'Ship in Q4',
      agendaItemId: 'ai-1',
      sourceSpanId: 'span-1',
      state: 'confirmed',
    },
    ENDED,
  )
  actionRepo(db).insert(
    { id: 'a-1', agendaItemId: 'ai-1', sourceSpanId: 'span-1', status: 'open', state: 'proposed' },
    ENDED,
  )
  discussionSummaryRepo(db).insert({ id: 's-1', agendaItemId: 'ai-1', text: 'Besproken' }, ENDED)
}

function seedDraftMeeting(db: Database.Database): void {
  meetingRepo(db).insert({
    id: DRAFT,
    title: 'Nog niet gestart',
    state: 'draft',
    source: 'live',
    paused: false,
    createdAt: '2026-07-04T09:00:00.000Z',
    primaryLanguage: 'nl',
    titleAutoGenerated: false,
  })
}

describe('MeetingQueryService', () => {
  let db: Database.Database

  beforeEach(() => {
    db = openDb()
    seedEndedMeeting(db)
    seedDraftMeeting(db)
  })

  it('list() returns meetings that are not Draft', () => {
    const ids = build(db)
      .list()
      .map((m) => m.id)
    expect(ids).toEqual([ENDED])
  })

  it('load() assembles the meeting with all its child collections', () => {
    const loaded = build(db).load(ENDED)
    expect(loaded).not.toBeNull()
    expect(loaded?.meeting.id).toBe(ENDED)
    expect(loaded?.decisions.map((d) => d.id)).toEqual(['d-1'])
    expect(loaded?.actions.map((a) => a.id)).toEqual(['a-1'])
    expect(loaded?.agendaItems.map((a) => a.id)).toEqual(['ai-1'])
    expect(loaded?.participants.map((p) => p.id)).toEqual(['p-1'])
    expect(loaded?.summaries.map((s) => s.id)).toEqual(['s-1'])
  })

  it('load() returns null for an unknown meeting', () => {
    expect(build(db).load('nope')).toBeNull()
  })

  it('delete() removes the meeting so list() no longer returns it', () => {
    build(db).delete(ENDED)
    expect(build(db).list()).toHaveLength(0)
  })

  it('transcriptText() renders the meeting spans as plain text', () => {
    const text = build(db).transcriptText(ENDED)
    expect(text).toContain('Hallo allemaal')
    expect(text).toContain('We beginnen')
  })
})
