/**
 * The Steno wordmark, shown in the persistent chrome (App.tsx).
 *
 * The flat pencil->ink gradient variant (no sketch texture) is used here: at
 * chrome size the texture would only muddy, while the cool-grey-to-bronze hue
 * still carries the "pencil to ink" idea. The SVG is bundled as an asset URL and
 * rendered as an <img>; the accessible name comes from i18n so the wordmark
 * reads as "Steno" to assistive tech. Asset is regenerated by
 * docs/design/generate-brand.py (single source of truth).
 */

import React from 'react'

import wordmark from '../assets/steno-wordmark.svg'
import { t } from '../i18n'

export function Wordmark(): React.JSX.Element {
  return <img className="app-wordmark" src={wordmark} alt={t('app.name')} draggable={false} />
}
