/**
 * @vitest-environment node
 *
 * Tests for finalizeMeetingEnd — the "transition Live -> Ended if still live"
 * guard duplicated in LiveSessionController.endMeeting and
 * ImportSessionController.finish (review item 5). It runs the final pass's
 * downstream: mark the meeting Ended through the single enforcer, once.
 */
import Database from 'better-sqlite3'
import { describe, it, expect, beforeEach } from 'vitest'

import { FakeClock } from '@shared/providers'

import { runMigrations } from '../db/migrate'
import { meetingRepo } from '../db/repos/meetingRepo'
import { MeetingLifecycleService } from '../services/meetingLifecycleService'

import { finalizeMeetingEnd } from './finalizeMeetingEnd'

const MEETING_ID = 'mtg-1'

function openDb(state: 'live' | 'ended'): Database.Database {
  const db = new Database(':memory:')
  db.pragma('foreign_keys = ON')
  runMigrations(db)
  meetingRepo(db).insert({
    id: MEETING_ID,
    title: 'Test',
    state,
    source: 'live',
    paused: false,
    createdAt: '2026-07-04T10:00:00.000Z',
    startedAt: '2026-07-04T10:00:00.000Z',
    primaryLanguage: 'nl',
    titleAutoGenerated: false,
  })
  return db
}

describe('finalizeMeetingEnd', () => {
  let db: Database.Database
  let mRepo: ReturnType<typeof meetingRepo>
  let lifecycle: MeetingLifecycleService

  function setup(state: 'live' | 'ended'): void {
    db = openDb(state)
    mRepo = meetingRepo(db)
    lifecycle = new MeetingLifecycleService(mRepo, new FakeClock(0))
  }

  beforeEach(() => {
    setup('live')
  })

  it('transitions a still-Live meeting to Ended', () => {
    finalizeMeetingEnd(mRepo, lifecycle, MEETING_ID)
    expect(mRepo.findById(MEETING_ID)?.state).toBe('ended')
  })

  it('is a no-op when the meeting is already Ended (no double-end)', () => {
    setup('ended')
    finalizeMeetingEnd(mRepo, lifecycle, MEETING_ID)
    expect(mRepo.findById(MEETING_ID)?.state).toBe('ended')
  })

  it('is a no-op for an unknown meeting', () => {
    expect(() => {
      finalizeMeetingEnd(mRepo, lifecycle, 'nope')
    }).not.toThrow()
  })
})
