/**
 * Item 0013 — Zustand store tests.
 *
 * Coverage:
 *   1. Store initializes with route = 'draft' and activeMeeting = null.
 *   2. setRoute updates the route.
 *   3. setActiveMeeting stores and clears the meeting slot.
 */

import { describe, it, expect, beforeEach } from 'vitest'

import { useAppStore, type AppRoute } from '../store/appStore'

beforeEach(() => {
  useAppStore.setState({ route: 'draft', activeMeeting: null })
})

describe('appStore — initial state', () => {
  it('starts with route = "draft"', () => {
    expect(useAppStore.getState().route).toBe('draft')
  })

  it('starts with activeMeeting = null', () => {
    expect(useAppStore.getState().activeMeeting).toBeNull()
  })
})

describe('appStore — setRoute', () => {
  it('updates route to "live"', () => {
    useAppStore.getState().setRoute('live')
    expect(useAppStore.getState().route).toBe('live')
  })

  it('updates route to "review"', () => {
    useAppStore.getState().setRoute('review')
    expect(useAppStore.getState().route).toBe('review')
  })

  it('updates route back to "draft"', () => {
    useAppStore.getState().setRoute('live')
    useAppStore.getState().setRoute('draft')
    expect(useAppStore.getState().route).toBe('draft')
  })
})

describe('appStore — setActiveMeeting', () => {
  it('stores a meeting id', () => {
    useAppStore.getState().setActiveMeeting('mtg-001')
    expect(useAppStore.getState().activeMeeting).toBe('mtg-001')
  })

  it('clears the meeting by setting null', () => {
    useAppStore.getState().setActiveMeeting('mtg-001')
    useAppStore.getState().setActiveMeeting(null)
    expect(useAppStore.getState().activeMeeting).toBeNull()
  })
})

// Type test — AppRoute must be exactly these three values
const _routeCheck: AppRoute[] = ['draft', 'live', 'review']
void _routeCheck

// ---------------------------------------------------------------------------
// appStore — loadMeeting keeps Proposed items (Review must show them so the
// note-taker can confirm the final pass's output, not just already-confirmed)
// ---------------------------------------------------------------------------

describe('appStore — loadMeeting', () => {
  const meeting = {
    id: 'mtg-1',
    title: 'Vergadering',
    state: 'ended' as const,
    source: 'live' as const,
    paused: false,
    createdAt: '2026-07-04T10:00:00.000Z',
    primaryLanguage: 'nl',
    titleAutoGenerated: false,
  }

  const payload = {
    meeting,
    decisions: [
      {
        id: 'd-p',
        rationale: 'Voorstel',
        agendaItemId: 'ai-1',
        sourceSpanId: 's1',
        state: 'proposed' as const,
      },
      {
        id: 'd-c',
        rationale: 'Bevestigd',
        agendaItemId: 'ai-1',
        sourceSpanId: 's2',
        state: 'confirmed' as const,
      },
    ],
    actions: [
      {
        id: 'a-p',
        agendaItemId: 'ai-1',
        sourceSpanId: 's1',
        status: 'open' as const,
        state: 'proposed' as const,
      },
    ],
    agendaItems: [],
    participants: [],
    summaries: [],
  }

  beforeEach(() => {
    Object.assign(window, { api: { meetingLoad: () => Promise.resolve(payload) } })
    useAppStore.setState({
      proposedDecisions: [],
      proposedActions: [],
      confirmedDecisions: [],
      confirmedActions: [],
    })
  })

  it('populates Proposed and Confirmed decisions/actions separately', async () => {
    await useAppStore.getState().loadMeeting('mtg-1')
    const s = useAppStore.getState()
    expect(s.proposedDecisions.map((d) => d.id)).toEqual(['d-p'])
    expect(s.confirmedDecisions.map((d) => d.id)).toEqual(['d-c'])
    expect(s.proposedActions.map((a) => a.id)).toEqual(['a-p'])
    expect(s.confirmedActions).toEqual([])
  })
})

// ---------------------------------------------------------------------------
// appStore — discussionSummaries (item 0021)
// ---------------------------------------------------------------------------

describe('appStore — discussionSummaries', () => {
  beforeEach(() => {
    useAppStore.setState({ discussionSummaries: [] })
  })

  it('starts with an empty discussionSummaries array', () => {
    expect(useAppStore.getState().discussionSummaries).toEqual([])
  })

  it('setDiscussionSummaries stores the summaries', () => {
    const summaries = [
      { id: 's-1', agendaItemId: 'ai-1', text: 'De groep besloot door te gaan.' },
      { id: 's-2', agendaItemId: 'ai-2', text: 'Budget goedgekeurd.' },
    ]
    useAppStore.getState().setDiscussionSummaries(summaries)
    expect(useAppStore.getState().discussionSummaries).toEqual(summaries)
  })

  it('setDiscussionSummaries replaces the previous set', () => {
    useAppStore
      .getState()
      .setDiscussionSummaries([{ id: 's-1', agendaItemId: 'ai-1', text: 'Eerste ronde.' }])
    useAppStore
      .getState()
      .setDiscussionSummaries([{ id: 's-2', agendaItemId: 'ai-2', text: 'Tweede ronde.' }])
    const summaries = useAppStore.getState().discussionSummaries
    expect(summaries).toHaveLength(1)
    expect(summaries[0]).toHaveProperty('id', 's-2')
  })
})
