/**
 * Boundary DTOs for the provider ports (item 0005).
 *
 * These are the Zod-validated contracts that cross the provider boundary.
 * All LLM and ASR output is parsed through these schemas before it enters
 * the domain (principle #8 — validate at every boundary with Zod).
 *
 * TypeScript types are derived via z.infer — schemas are the single source
 * of truth, types follow automatically.
 */

import { z } from 'zod'

import { AgendaItemSchema, ParticipantSchema, TranscriptSpanSchema } from '../domain/types'

// ============================================================================
// PROPOSED DECISION — what the ExtractionProvider suggests
// ============================================================================

/**
 * A Decision candidate returned by the ExtractionProvider. Vendor-neutral:
 * no domain IDs are assigned here. The item lifecycle service (0007) turns
 * these into real Decision domain objects.
 */
export const ProposedDecisionSchema = z.object({
  /** The rationale text extracted from the transcript. */
  rationale: z.string(),
  /** The span from which this decision was derived. */
  sourceSpanId: z.string().min(1),
  /**
   * Optional hint toward an Agenda Item. The owner-assignment logic (0009)
   * resolves this against the actual agenda; the provider is not authoritative.
   */
  agendaItemHint: z.string().optional(),
})

export type ProposedDecision = z.infer<typeof ProposedDecisionSchema>

// ============================================================================
// PROPOSED ACTION — what the ExtractionProvider suggests
// ============================================================================

/**
 * An Action candidate returned by the ExtractionProvider. Owner and agenda
 * assignment are hints only; validated by the assignment logic in item 0009.
 */
export const ProposedActionSchema = z.object({
  /** Human-readable description of the action. */
  description: z.string().min(1),
  /** The span from which this action was derived. */
  sourceSpanId: z.string().min(1),
  /**
   * Optional name hint for the owner. Must be fuzzy-matched against the
   * Participant list before use; never stored raw.
   */
  ownerHint: z.string().optional(),
  /**
   * Optional hint toward an Agenda Item (same caveat as ProposedDecision).
   */
  agendaItemHint: z.string().optional(),
})

export type ProposedAction = z.infer<typeof ProposedActionSchema>

// ============================================================================
// DISCUSSION SUMMARY DTO — produced only on the final pass
// ============================================================================

/**
 * A per-Agenda-Item discussion summary generated by the final extraction pass.
 * Per CONTEXT.md: "never live — generated when the Meeting reaches Ended".
 */
export const ProposedDiscussionSummarySchema = z.object({
  /** The Agenda Item this summary covers. */
  agendaItemId: z.string().min(1),
  /** The summary text. */
  text: z.string(),
})

export type ProposedDiscussionSummary = z.infer<typeof ProposedDiscussionSummarySchema>

// ============================================================================
// EXTRACTION REQUEST — what goes in to the ExtractionProvider
// ============================================================================

export const ExtractionRequestSchema = z.object({
  /** The transcript spans accumulated since the last extraction turn (or all spans on the final pass). */
  spans: z.array(TranscriptSpanSchema),
  /** The agenda items for the meeting, fed as context. */
  agendaItems: z.array(AgendaItemSchema),
  /** The participants, fed as context for owner-hint matching. */
  participants: z.array(ParticipantSchema),
  /** The primary language of the meeting, e.g. 'nl' or 'en'. */
  primaryLanguage: z.string().min(1),
  /**
   * True on the final pass (Meeting → Ended); the provider should also
   * produce per-Agenda-Item discussion summaries in that case.
   */
  isFinalPass: z.boolean(),
})

export type ExtractionRequest = z.infer<typeof ExtractionRequestSchema>

// ============================================================================
// EXTRACTION RESPONSE — what comes out of the ExtractionProvider
// ============================================================================

export const ExtractionResponseSchema = z.object({
  /** Decisions proposed by the provider for this turn. May be empty. */
  proposedDecisions: z.array(ProposedDecisionSchema),
  /** Actions proposed by the provider for this turn. May be empty. */
  proposedActions: z.array(ProposedActionSchema),
  /**
   * Discussion summaries, present only on the final pass.
   * Absent (undefined) for normal rolling extractions.
   */
  discussionSummaries: z.array(ProposedDiscussionSummarySchema).optional(),
})

export type ExtractionResponse = z.infer<typeof ExtractionResponseSchema>

// ============================================================================
// INFERRED CONTEXT — agenda + participants derived from a transcript (0026)
// ============================================================================

/**
 * Agenda Items and Participants the ExtractionProvider inferred from a whole
 * transcript, used for an Imported Meeting when the user did not supply them.
 *
 * Vendor-neutral and minimal: no domain IDs (assigned downstream), just the
 * fields the user would otherwise have typed in Draft. Both lists may be empty
 * when nothing could be inferred. See ADR 0026.
 */
export const InferredContextSchema = z.object({
  /** Agenda Items inferred from the transcript. */
  agendaItems: z.array(z.object({ title: z.string().min(1), topic: z.string().min(1) })),
  /** Participants inferred from the transcript. */
  participants: z.array(z.object({ name: z.string().min(1) })),
  /**
   * A meeting title inferred from the source. Only produced when inferring over
   * a whole transcript or pasted text (paste-time / final pass); the live tick
   * ignores it. Optional — absent when no title could be inferred.
   */
  title: z.string().min(1).optional(),
})

export type InferredContext = z.infer<typeof InferredContextSchema>
