import { describe, expect, it } from 'vitest'

import {
  PingRequestSchema,
  PingResponseSchema,
  MeetingCreateRequestSchema,
  MeetingEndRequestSchema,
  MeetingEndResponseSchema,
  ImportStartRequestSchema,
  ImportStartResponseSchema,
  ImportFinishRequestSchema,
  ImportProgressEventSchema,
  ContextInferFromTextRequestSchema,
  ContextInferFromTextResponseSchema,
  AgendaChangedPayloadSchema,
  AgendaItemConfirmRequestSchema,
  AgendaItemEditAndConfirmRequestSchema,
  type IpcChannel,
} from './ipc'

// Slice 1 — Zod schema validation: valid payloads parse, invalid ones throw

describe('PingRequestSchema', () => {
  it('parses a valid empty-object ping request', () => {
    const result = PingRequestSchema.parse({})
    expect(result).toEqual({})
  })

  it('rejects a non-object payload', () => {
    expect(() => PingRequestSchema.parse('not-an-object')).toThrow()
  })
})

describe('PingResponseSchema', () => {
  it('parses a valid pong response', () => {
    const result = PingResponseSchema.parse({ pong: true })
    expect(result).toEqual({ pong: true })
  })

  it('rejects a response missing the pong field', () => {
    expect(() => PingResponseSchema.parse({})).toThrow()
  })

  it('rejects pong set to false', () => {
    expect(() => PingResponseSchema.parse({ pong: false })).toThrow()
  })
})

// Quick-start — meeting:create gains titleAutoGenerated (ADR 0029)

describe('MeetingCreateRequestSchema', () => {
  it('defaults titleAutoGenerated to false when absent', () => {
    const result = MeetingCreateRequestSchema.parse({ title: 'Q3', primaryLanguage: 'nl' })
    expect(result.titleAutoGenerated).toBe(false)
  })

  it('accepts titleAutoGenerated true (quick-start)', () => {
    const result = MeetingCreateRequestSchema.parse({
      title: 'Vergadering 25 jun 2026 09:00',
      primaryLanguage: 'nl',
      titleAutoGenerated: true,
    })
    expect(result.titleAutoGenerated).toBe(true)
  })
})

// Slice 2 — meeting:end schema (item 0021)

describe('MeetingEndRequestSchema', () => {
  it('parses a valid end-meeting request with a meetingId', () => {
    const result = MeetingEndRequestSchema.parse({ meetingId: 'mtg-123' })
    expect(result).toEqual({ meetingId: 'mtg-123' })
  })

  it('rejects when meetingId is empty', () => {
    expect(() => MeetingEndRequestSchema.parse({ meetingId: '' })).toThrow()
  })

  it('rejects when meetingId is missing', () => {
    expect(() => MeetingEndRequestSchema.parse({})).toThrow()
  })
})

describe('MeetingEndResponseSchema', () => {
  it('parses a valid end-meeting response', () => {
    const result = MeetingEndResponseSchema.parse({ ok: true })
    expect(result).toEqual({ ok: true })
  })

  it('rejects when ok is false', () => {
    expect(() => MeetingEndResponseSchema.parse({ ok: false })).toThrow()
  })
})

// Slice 3 — import channels (item 0026)

describe('ImportStartRequestSchema', () => {
  const valid = {
    title: 'Geïmporteerde opname',
    primaryLanguage: 'nl',
    agendaItems: [{ title: 'Planning', topic: 'Q3' }],
    participants: [{ name: 'Jeroen' }],
    inferContext: false,
  }

  it('parses a valid import-start request', () => {
    expect(ImportStartRequestSchema.parse(valid)).toEqual(valid)
  })

  it('allows empty agenda + participants (inference path)', () => {
    const result = ImportStartRequestSchema.parse({
      ...valid,
      agendaItems: [],
      participants: [],
      inferContext: true,
    })
    expect(result.inferContext).toBe(true)
  })

  it('rejects an empty title', () => {
    expect(() => ImportStartRequestSchema.parse({ ...valid, title: '' })).toThrow()
  })

  it('rejects an agenda item with an empty topic', () => {
    expect(() =>
      ImportStartRequestSchema.parse({ ...valid, agendaItems: [{ title: 'x', topic: '' }] }),
    ).toThrow()
  })

  it('rejects a missing inferContext flag', () => {
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    const { inferContext: _drop, ...rest } = valid
    expect(() => ImportStartRequestSchema.parse(rest)).toThrow()
  })
})

describe('ImportStartResponseSchema', () => {
  it('parses a response carrying the new meeting id', () => {
    expect(ImportStartResponseSchema.parse({ meetingId: 'imp-1' })).toEqual({ meetingId: 'imp-1' })
  })

  it('rejects an empty meeting id', () => {
    expect(() => ImportStartResponseSchema.parse({ meetingId: '' })).toThrow()
  })
})

describe('ImportFinishRequestSchema', () => {
  it('parses a valid finish request', () => {
    expect(ImportFinishRequestSchema.parse({ meetingId: 'imp-1' })).toEqual({ meetingId: 'imp-1' })
  })

  it('rejects a missing meeting id', () => {
    expect(() => ImportFinishRequestSchema.parse({})).toThrow()
  })
})

describe('ImportProgressEventSchema', () => {
  it('parses each known stage', () => {
    for (const stage of ['transcribing', 'inferring', 'extracting', 'done', 'error'] as const) {
      expect(ImportProgressEventSchema.parse({ stage }).stage).toBe(stage)
    }
  })

  it('allows an optional percent and error', () => {
    const result = ImportProgressEventSchema.parse({ stage: 'error', error: 'no key', percent: 50 })
    expect(result.error).toBe('no key')
    expect(result.percent).toBe(50)
  })

  it('rejects an unknown stage', () => {
    expect(() => ImportProgressEventSchema.parse({ stage: 'pondering' })).toThrow()
  })
})

// Slice 2 — context:inferFromText (paste an agenda, ADR 0029)

describe('ContextInferFromTextRequestSchema', () => {
  it('parses a valid paste request', () => {
    const result = ContextInferFromTextRequestSchema.parse({
      text: 'Agenda: begroting bespreken',
      primaryLanguage: 'nl',
    })
    expect(result.text).toBe('Agenda: begroting bespreken')
    expect(result.primaryLanguage).toBe('nl')
  })

  it('rejects empty text', () => {
    expect(() =>
      ContextInferFromTextRequestSchema.parse({ text: '', primaryLanguage: 'nl' }),
    ).toThrow()
  })

  it('rejects a missing primary language', () => {
    expect(() => ContextInferFromTextRequestSchema.parse({ text: 'Agenda' })).toThrow()
  })
})

describe('ContextInferFromTextResponseSchema', () => {
  it('parses an inferred context with an optional title', () => {
    const result = ContextInferFromTextResponseSchema.parse({
      agendaItems: [{ title: 'Begroting', topic: 'Q3' }],
      participants: [{ name: 'Jeroen' }],
      title: 'Begrotingsoverleg',
    })
    expect(result.agendaItems[0]?.title).toBe('Begroting')
    expect(result.title).toBe('Begrotingsoverleg')
  })

  it('parses an empty inferred context (nothing could be inferred)', () => {
    expect(ContextInferFromTextResponseSchema.parse({ agendaItems: [], participants: [] })).toEqual(
      {
        agendaItems: [],
        participants: [],
      },
    )
  })

  it('rejects an agenda item with an empty title', () => {
    expect(() =>
      ContextInferFromTextResponseSchema.parse({
        agendaItems: [{ title: '', topic: 'x' }],
        participants: [],
      }),
    ).toThrow()
  })
})

describe('IpcChannel', () => {
  it('includes the context:inferFromText channel name', () => {
    const channel: IpcChannel = 'context:inferFromText'
    expect(channel).toBe('context:inferFromText')
  })

  it('includes the agenda confirm/edit channel names', () => {
    const confirm: IpcChannel = 'agendaItem:confirm'
    const edit: IpcChannel = 'agendaItem:editAndConfirm'
    expect([confirm, edit]).toEqual(['agendaItem:confirm', 'agendaItem:editAndConfirm'])
  })
})

// Slice 4 — live agenda grooming (ADR 0029)

describe('AgendaChangedPayloadSchema', () => {
  it('parses a payload carrying the current agenda', () => {
    const result = AgendaChangedPayloadSchema.parse({
      agendaItems: [
        { id: 'ai-1', title: 'Begroting', topic: 'Q3', state: 'proposed' },
        { id: 'ai-2', title: 'Planning', topic: 'Later', state: 'confirmed' },
      ],
    })
    expect(result.agendaItems).toHaveLength(2)
    expect(result.agendaItems[0]?.state).toBe('proposed')
  })

  it('rejects an agenda item with an unknown state', () => {
    expect(() =>
      AgendaChangedPayloadSchema.parse({
        agendaItems: [{ id: 'ai-1', title: 'x', topic: 'y', state: 'archived' }],
      }),
    ).toThrow()
  })
})

describe('AgendaItemConfirmRequestSchema', () => {
  it('parses a valid confirm request', () => {
    expect(AgendaItemConfirmRequestSchema.parse({ agendaItemId: 'ai-1' })).toEqual({
      agendaItemId: 'ai-1',
    })
  })

  it('rejects an empty agenda item id', () => {
    expect(() => AgendaItemConfirmRequestSchema.parse({ agendaItemId: '' })).toThrow()
  })
})

describe('AgendaItemEditAndConfirmRequestSchema', () => {
  it('parses a valid edit-and-confirm request', () => {
    const result = AgendaItemEditAndConfirmRequestSchema.parse({
      agendaItemId: 'ai-1',
      title: 'Nieuwe titel',
      topic: 'Nieuw onderwerp',
    })
    expect(result.title).toBe('Nieuwe titel')
  })

  it('rejects an empty title', () => {
    expect(() =>
      AgendaItemEditAndConfirmRequestSchema.parse({
        agendaItemId: 'ai-1',
        title: '',
        topic: 'x',
      }),
    ).toThrow()
  })
})
