/**
 * IPC contract for main ↔ renderer communication.
 *
 * Channel names, request types, and response types are all defined here.
 * The renderer never touches ipcRenderer directly — everything goes through
 * the typed preload bridge (window.api).
 *
 * Zod schemas serve as the single source of truth; TypeScript types are
 * derived from them via z.infer.
 */

import { z } from 'zod'

import { MeetingSchema, AgendaItemSchema, ParticipantSchema } from './domain'
import { DecisionSchema, ActionSchema, DiscussionSummarySchema, NudgeSchema } from './domain/types'
import { InferredContextSchema } from './providers'
import { type EgressState } from './settings/egressState'
import { AppSettingsSchema } from './settings/settingsSchema'

// ---------------------------------------------------------------------------
// ping — smoke-test channel proving the bridge is alive
// ---------------------------------------------------------------------------

export const PingRequestSchema = z.object({})

export const PingResponseSchema = z.object({
  pong: z.literal(true),
})

export type PingRequest = z.infer<typeof PingRequestSchema>
export type PingResponse = z.infer<typeof PingResponseSchema>

// ---------------------------------------------------------------------------
// settings:get — retrieve current persisted settings
// ---------------------------------------------------------------------------

export const SettingsGetRequestSchema = z.object({})
export const SettingsGetResponseSchema = AppSettingsSchema

export type SettingsGetRequest = z.infer<typeof SettingsGetRequestSchema>
export type SettingsGetResponse = z.infer<typeof SettingsGetResponseSchema>

// ---------------------------------------------------------------------------
// settings:set — persist new settings (partial updates not supported;
// always send the full settings object)
// ---------------------------------------------------------------------------

export const SettingsSetRequestSchema = AppSettingsSchema
export const SettingsSetResponseSchema = z.object({ ok: z.literal(true) })

export type SettingsSetRequest = z.infer<typeof SettingsSetRequestSchema>
export type SettingsSetResponse = z.infer<typeof SettingsSetResponseSchema>

// ---------------------------------------------------------------------------
// egress:state — derive the current egress state from persisted settings
// ---------------------------------------------------------------------------

export const EgressStateGetRequestSchema = z.object({})

/**
 * EgressState is serialised over IPC as a plain object. We re-validate it
 * on the renderer side via this schema (principle #8 — validate at every
 * boundary).
 */
export const EgressStateGetResponseSchema = z.object({
  audio: z.union([z.literal('local'), z.string().startsWith('cloud:')]),
  notes: z.string().startsWith('cloud:'),
})

export type EgressStateGetRequest = z.infer<typeof EgressStateGetRequestSchema>
// Re-export EgressState as the IPC response type so the renderer can use it
export type { EgressState }

// ---------------------------------------------------------------------------
// meeting:create — create a new meeting in draft state (item 0014)
// ---------------------------------------------------------------------------

export const MeetingCreateRequestSchema = z.object({
  title: z.string().min(1, 'Meeting title cannot be empty'),
  primaryLanguage: z.string().min(1, 'Primary language cannot be empty'),
  /**
   * Whether `title` is an auto-generated placeholder (the "Direct starten"
   * quick-start path). Defaults to false for a normal user-set title. ADR 0029.
   */
  titleAutoGenerated: z.boolean().default(false),
})

export const MeetingCreateResponseSchema = MeetingSchema

export type MeetingCreateRequest = z.infer<typeof MeetingCreateRequestSchema>
export type MeetingCreateResponse = z.infer<typeof MeetingCreateResponseSchema>

// ---------------------------------------------------------------------------
// agendaItem:add — add an agenda item to a meeting (item 0014)
// ---------------------------------------------------------------------------

export const AgendaItemAddRequestSchema = z.object({
  meetingId: z.string().min(1, 'Meeting ID cannot be empty'),
  title: z.string().min(1, 'Agenda item title cannot be empty'),
  topic: z.string().min(1, 'Agenda item topic cannot be empty'),
})

export const AgendaItemAddResponseSchema = AgendaItemSchema

export type AgendaItemAddRequest = z.infer<typeof AgendaItemAddRequestSchema>
export type AgendaItemAddResponse = z.infer<typeof AgendaItemAddResponseSchema>

// ---------------------------------------------------------------------------
// agendaItem:remove — remove an agenda item (item 0014)
// ---------------------------------------------------------------------------

export const AgendaItemRemoveRequestSchema = z.object({
  agendaItemId: z.string().min(1, 'Agenda item ID cannot be empty'),
})

export const AgendaItemRemoveResponseSchema = z.object({ ok: z.literal(true) })

export type AgendaItemRemoveRequest = z.infer<typeof AgendaItemRemoveRequestSchema>
export type AgendaItemRemoveResponse = z.infer<typeof AgendaItemRemoveResponseSchema>

// ---------------------------------------------------------------------------
// participant:add — add a participant to a meeting (item 0014)
// ---------------------------------------------------------------------------

export const ParticipantAddRequestSchema = z.object({
  meetingId: z.string().min(1, 'Meeting ID cannot be empty'),
  name: z.string().min(1, 'Participant name cannot be empty'),
})

export const ParticipantAddResponseSchema = ParticipantSchema

export type ParticipantAddRequest = z.infer<typeof ParticipantAddRequestSchema>
export type ParticipantAddResponse = z.infer<typeof ParticipantAddResponseSchema>

// ---------------------------------------------------------------------------
// participant:remove — remove a participant (item 0014)
// ---------------------------------------------------------------------------

export const ParticipantRemoveRequestSchema = z.object({
  participantId: z.string().min(1, 'Participant ID cannot be empty'),
})

export const ParticipantRemoveResponseSchema = z.object({ ok: z.literal(true) })

export type ParticipantRemoveRequest = z.infer<typeof ParticipantRemoveRequestSchema>
export type ParticipantRemoveResponse = z.infer<typeof ParticipantRemoveResponseSchema>

// ---------------------------------------------------------------------------
// meeting:start — transition a draft meeting to live (item 0014)
// ---------------------------------------------------------------------------

export const MeetingStartRequestSchema = z.object({
  meetingId: z.string().min(1, 'Meeting ID cannot be empty'),
})

export const MeetingStartResponseSchema = MeetingSchema

export type MeetingStartRequest = z.infer<typeof MeetingStartRequestSchema>
export type MeetingStartResponse = z.infer<typeof MeetingStartResponseSchema>

// ---------------------------------------------------------------------------
// provider:testConnection — probe the configured provider's credentials (5.1)
//
// One cheap auth/reachability round-trip (models/projects listing) so the user
// sees auth/URL errors at config time. Never returns or logs the key. The error
// string is a short code (e.g. 'HTTP 401', 'no-key', 'network').
// ---------------------------------------------------------------------------

export const ProviderTestConnectionRequestSchema = z.object({
  role: z.enum(['asr', 'extraction']),
})

export const ProviderTestConnectionResponseSchema = z.union([
  z.object({ ok: z.literal(true) }),
  z.object({ ok: z.literal(false), error: z.string() }),
])

export type ProviderTestConnectionRequest = z.infer<typeof ProviderTestConnectionRequestSchema>
export type ProviderTestConnectionResponse = z.infer<typeof ProviderTestConnectionResponseSchema>

// ---------------------------------------------------------------------------
// audio:start — tell main to open an ASR session (item 0015)
// ---------------------------------------------------------------------------

export const AudioStartRequestSchema = z.object({ meetingId: z.string().min(1) })
export const AudioStartResponseSchema = z.object({ ok: z.literal(true) })

export type AudioStartRequest = z.infer<typeof AudioStartRequestSchema>
export type AudioStartResponse = z.infer<typeof AudioStartResponseSchema>

// ---------------------------------------------------------------------------
// secret:set — write an API key into safeStorage (item 0016)
//
// The renderer sends the key value exactly once during the user's key-entry
// flow. Main encrypts it via safeStorage and stores it; the value is never
// sent back to the renderer. There is deliberately NO secret:get channel.
// ---------------------------------------------------------------------------

export const SecretSetRequestSchema = z.object({
  /** Stable key name used to look up the secret (e.g. 'deepgram', 'anthropic'). */
  key: z.string().min(1),
  /** The raw API key value — encrypted by main, never stored in settings JSON. */
  value: z.string().min(1),
})

export const SecretSetResponseSchema = z.object({ ok: z.literal(true) })

export type SecretSetRequest = z.infer<typeof SecretSetRequestSchema>
export type SecretSetResponse = z.infer<typeof SecretSetResponseSchema>

// ---------------------------------------------------------------------------
// secret:has — check whether a key is present in safeStorage (item 0016)
//
// Returns a boolean presence flag. Never returns the key value.
// ---------------------------------------------------------------------------

export const SecretHasRequestSchema = z.object({
  key: z.string().min(1),
})

export const SecretHasResponseSchema = z.object({
  /** true if a secret is stored for this key, false otherwise. */
  has: z.boolean(),
})

export type SecretHasRequest = z.infer<typeof SecretHasRequestSchema>
export type SecretHasResponse = z.infer<typeof SecretHasResponseSchema>

// ---------------------------------------------------------------------------
// audio:stop — tell main to close the active ASR session (item 0015)
// ---------------------------------------------------------------------------

export const AudioStopRequestSchema = z.object({})
export const AudioStopResponseSchema = z.object({ ok: z.literal(true) })

export type AudioStopRequest = z.infer<typeof AudioStopRequestSchema>
export type AudioStopResponse = z.infer<typeof AudioStopResponseSchema>

// ---------------------------------------------------------------------------
// transcript:span — main → renderer event (item 0015)
//
// NOT an invoke channel. Main pushes spans via webContents.send; the preload
// exposes onTranscriptSpan(cb) / offTranscriptSpan(cb) for the renderer.
// We validate the incoming payload with this schema on the renderer side.
// ---------------------------------------------------------------------------

export { TranscriptSpanSchema } from './domain/types'
export type { TranscriptSpan } from './domain/types'

// ---------------------------------------------------------------------------
// items:changed — main → renderer push event (item 0018)
//
// Emitted after ANY item mutation (an agent extraction turn OR a note-taker IPC
// action: confirm / dismiss / edit / create). Main is authoritative: the payload
// carries the FULL current item set for `meetingId` (both Proposed and Confirmed),
// so the renderer reconciles wholesale by state rather than re-deriving
// transitions locally (ADR 0033). The renderer applies it only when `meetingId`
// matches the meeting it currently has focused.
//
// Pattern: webContents.send('items:changed', payload) on main;
//          ipcRenderer.on('items:changed', listener) in preload, exposed as
//          window.api.onItemsChanged(cb) returning an UnsubscribeFn.
// ---------------------------------------------------------------------------

export { DecisionSchema, ActionSchema, DiscussionSummarySchema, NudgeSchema } from './domain/types'
export type { Decision, Action, DiscussionSummary, Nudge } from './domain/types'

export const ItemsChangedPayloadSchema = z.object({
  /** The meeting these items belong to (renderer applies only for its focused meeting). */
  meetingId: z.string().min(1),
  /** Full current decisions for the meeting (both Proposed and Confirmed). */
  decisions: z.array(
    z.object({
      id: z.string().min(1),
      rationale: z.string(),
      agendaItemId: z.string().min(1),
      sourceSpanId: z.string().min(1),
      state: z.enum(['proposed', 'confirmed']),
    }),
  ),
  /** Full current actions for the meeting (both Proposed and Confirmed). */
  actions: z.array(
    z.object({
      id: z.string().min(1),
      description: z.string().optional(),
      agendaItemId: z.string().min(1),
      sourceSpanId: z.string().min(1),
      owner: z.string().min(1).optional(),
      dueDate: z.iso.datetime().optional(),
      status: z.enum(['open', 'done']),
      state: z.enum(['proposed', 'confirmed']),
    }),
  ),
})

export type ItemsChangedPayload = z.infer<typeof ItemsChangedPayloadSchema>

// ---------------------------------------------------------------------------
// items:summaries — main → renderer push event (item 0018)
//
// Emitted exactly once after the final extraction pass completes (when the
// meeting ends). Carries all Discussion Summaries produced by the final pass.
// ---------------------------------------------------------------------------

export const ItemsSummariesPayloadSchema = z.object({
  summaries: z.array(
    z.object({
      id: z.string().min(1),
      agendaItemId: z.string().min(1),
      text: z.string(),
    }),
  ),
})

export type ItemsSummariesPayload = z.infer<typeof ItemsSummariesPayloadSchema>

// ---------------------------------------------------------------------------
// nudges:changed — main → renderer push event (item 0019)
//
// Emitted after every extraction turn (same timing as items:changed) and
// whenever note-taker actions change the confirmed set. Carries the full
// derived nudge array so the renderer can replace its local nudge state.
//
// Pattern: webContents.send('nudges:changed', payload) on main;
//          ipcRenderer.on('nudges:changed', listener) in preload, exposed as
//          window.api.onNudgesChanged(cb) returning an UnsubscribeFn.
// ---------------------------------------------------------------------------

export const NudgesChangedPayloadSchema = z.object({
  nudges: z.array(NudgeSchema),
})

export type NudgesChangedPayload = z.infer<typeof NudgesChangedPayloadSchema>

// ---------------------------------------------------------------------------
// summary:changed — main → renderer push event (item 0020)
//
// Emitted after each extraction cadence tick fires the summarise() call on the
// provider. Carries the latest whole-meeting plain-text running summary.
// The renderer replaces its local summary string on each event.
//
// Pattern: webContents.send('summary:changed', payload) on main;
//          ipcRenderer.on('summary:changed', listener) in preload, exposed as
//          window.api.onSummaryChanged(cb) returning an UnsubscribeFn.
// ---------------------------------------------------------------------------

export const SummaryChangedPayloadSchema = z.object({
  /** The latest whole-meeting running summary as plain text. */
  summary: z.string(),
})

export type SummaryChangedPayload = z.infer<typeof SummaryChangedPayloadSchema>

// ---------------------------------------------------------------------------
// summary:query — invoke channel (item 0020)
//
// The note-taker asks a free-form question grounded in the current transcript.
// Main calls provider.query() and returns a plain-text answer.
// If the provider has no query() method, returns { answer: '' }.
// ---------------------------------------------------------------------------

export const SummaryQueryRequestSchema = z.object({
  question: z.string().min(1, 'Question cannot be empty'),
})

export const SummaryQueryResponseSchema = z.object({
  answer: z.string(),
})

export type SummaryQueryRequest = z.infer<typeof SummaryQueryRequestSchema>
export type SummaryQueryResponse = z.infer<typeof SummaryQueryResponseSchema>

// ---------------------------------------------------------------------------
// item:confirm — note-taker confirms a Proposed Decision or Action (item 0018)
// ---------------------------------------------------------------------------

export const ItemConfirmRequestSchema = z.object({
  kind: z.enum(['decision', 'action']),
  id: z.string().min(1),
})

export const ItemConfirmResponseSchema = z.union([DecisionSchema, ActionSchema])

export type ItemConfirmRequest = z.infer<typeof ItemConfirmRequestSchema>
export type ItemConfirmResponse = z.infer<typeof ItemConfirmResponseSchema>

// ---------------------------------------------------------------------------
// item:editAndConfirm — edit + confirm in one step (item 0018)
// ---------------------------------------------------------------------------

const DecisionUpdatesSchema = z.object({
  rationale: z.string().optional(),
  agendaItemId: z.string().min(1).optional(),
})

const ActionUpdatesSchema = z.object({
  description: z.string().min(1).optional(),
  owner: z.string().min(1).optional(),
  dueDate: z.iso.datetime().optional(),
  status: z.enum(['open', 'done']).optional(),
  agendaItemId: z.string().min(1).optional(),
})

export const ItemEditAndConfirmRequestSchema = z.discriminatedUnion('kind', [
  z.object({ kind: z.literal('decision'), id: z.string().min(1), updates: DecisionUpdatesSchema }),
  z.object({ kind: z.literal('action'), id: z.string().min(1), updates: ActionUpdatesSchema }),
])

export const ItemEditAndConfirmResponseSchema = z.union([DecisionSchema, ActionSchema])

export type ItemEditAndConfirmRequest = z.infer<typeof ItemEditAndConfirmRequestSchema>
export type ItemEditAndConfirmResponse = z.infer<typeof ItemEditAndConfirmResponseSchema>

// ---------------------------------------------------------------------------
// item:dismiss — note-taker dismisses a Proposed Decision or Action (item 0018)
// ---------------------------------------------------------------------------

export const ItemDismissRequestSchema = z.object({
  kind: z.enum(['decision', 'action']),
  id: z.string().min(1),
})

export const ItemDismissResponseSchema = z.object({ ok: z.literal(true) })

export type ItemDismissRequest = z.infer<typeof ItemDismissRequestSchema>
export type ItemDismissResponse = z.infer<typeof ItemDismissResponseSchema>

// ---------------------------------------------------------------------------
// item:createConfirmed — manual add during Live → directly Confirmed (item 0018)
// ---------------------------------------------------------------------------

const NewDecisionItemSchema = z.object({
  id: z.string().min(1),
  rationale: z.string(),
  agendaItemId: z.string().min(1),
  sourceSpanId: z.string().min(1),
})

const NewActionItemSchema = z.object({
  id: z.string().min(1),
  description: z.string().optional(),
  agendaItemId: z.string().min(1),
  sourceSpanId: z.string().min(1),
  owner: z.string().min(1).optional(),
  dueDate: z.iso.datetime().optional(),
  status: z.enum(['open', 'done']),
})

export const ItemCreateConfirmedRequestSchema = z.discriminatedUnion('kind', [
  z.object({
    kind: z.literal('decision'),
    meetingId: z.string().min(1),
    item: NewDecisionItemSchema,
  }),
  z.object({
    kind: z.literal('action'),
    meetingId: z.string().min(1),
    item: NewActionItemSchema,
  }),
])

export const ItemCreateConfirmedResponseSchema = z.union([DecisionSchema, ActionSchema])

export type ItemCreateConfirmedRequest = z.infer<typeof ItemCreateConfirmedRequestSchema>
export type ItemCreateConfirmedResponse = z.infer<typeof ItemCreateConfirmedResponseSchema>

// ---------------------------------------------------------------------------
// meeting:end — end the active meeting, triggering the final extraction pass
// (item 0021)
// ---------------------------------------------------------------------------

export const MeetingEndRequestSchema = z.object({
  meetingId: z.string().min(1, 'Meeting ID cannot be empty'),
})

export const MeetingEndResponseSchema = z.object({ ok: z.literal(true) })

export type MeetingEndRequest = z.infer<typeof MeetingEndRequestSchema>
export type MeetingEndResponse = z.infer<typeof MeetingEndResponseSchema>

// ---------------------------------------------------------------------------
// export:markdown — save Markdown to a file chosen by the user (item 0022)
//
// Main shows a save dialog, writes the file, and returns ok/reason.
// The renderer generates the content string using the shared serializer.
// ---------------------------------------------------------------------------

export const ExportMarkdownRequestSchema = z.object({
  /** Pre-rendered Markdown content to write to disk. */
  content: z.string(),
})

export const ExportMarkdownResponseSchema = z.union([
  z.object({ ok: z.literal(true) }),
  z.object({ ok: z.literal(false), reason: z.string() }),
])

export type ExportMarkdownRequest = z.infer<typeof ExportMarkdownRequestSchema>
export type ExportMarkdownResponse = z.infer<typeof ExportMarkdownResponseSchema>

// ---------------------------------------------------------------------------
// export:copyMarkdown — copy Markdown to the clipboard (item 0022)
// ---------------------------------------------------------------------------

export const ExportCopyMarkdownRequestSchema = z.object({
  /** Pre-rendered Markdown content to copy to the clipboard. */
  content: z.string(),
})

export const ExportCopyMarkdownResponseSchema = z.object({ ok: z.literal(true) })

export type ExportCopyMarkdownRequest = z.infer<typeof ExportCopyMarkdownRequestSchema>
export type ExportCopyMarkdownResponse = z.infer<typeof ExportCopyMarkdownResponseSchema>

// ---------------------------------------------------------------------------
// transcript:copy — copy the full transcript to the clipboard (item 0026)
//
// Main reads the meeting's persisted spans, serialises them to plain text, and
// copies the result. The transcript never round-trips to the renderer; only the
// meeting id is sent.
// ---------------------------------------------------------------------------

export const TranscriptCopyRequestSchema = z.object({
  meetingId: z.string().min(1, 'Meeting ID cannot be empty'),
})

export const TranscriptCopyResponseSchema = z.object({ ok: z.literal(true) })

export type TranscriptCopyRequest = z.infer<typeof TranscriptCopyRequestSchema>
export type TranscriptCopyResponse = z.infer<typeof TranscriptCopyResponseSchema>

// ---------------------------------------------------------------------------
// meeting:list — returns all meetings ordered newest-first (item 0023)
// ---------------------------------------------------------------------------

export const MeetingListRequestSchema = z.object({})

export const MeetingListResponseSchema = z.object({
  meetings: z.array(MeetingSchema),
})

export type MeetingListRequest = z.infer<typeof MeetingListRequestSchema>
export type MeetingListResponse = z.infer<typeof MeetingListResponseSchema>

// ---------------------------------------------------------------------------
// meeting:load — load full state of a past meeting for review (item 0023)
//
// Returns the meeting + all its decisions, actions, agenda items, participants,
// and discussion summaries so the Review screen can render a reopened meeting.
// ---------------------------------------------------------------------------

export const MeetingLoadRequestSchema = z.object({
  meetingId: z.string().min(1, 'Meeting ID cannot be empty'),
})

export const MeetingLoadResponseSchema = z.object({
  meeting: MeetingSchema,
  decisions: z.array(DecisionSchema),
  actions: z.array(ActionSchema),
  agendaItems: z.array(AgendaItemSchema),
  participants: z.array(ParticipantSchema),
  summaries: z.array(DiscussionSummarySchema),
})

export type MeetingLoadRequest = z.infer<typeof MeetingLoadRequestSchema>
export type MeetingLoadResponse = z.infer<typeof MeetingLoadResponseSchema>

// ---------------------------------------------------------------------------
// meeting:delete — permanently delete a meeting and all its data (item 0026)
//
// Main deletes the meeting and cascade-deletes its agenda items, participants,
// transcript spans, decisions, actions, and discussion summaries.
// ---------------------------------------------------------------------------

export const MeetingDeleteRequestSchema = z.object({
  meetingId: z.string().min(1, 'Meeting ID cannot be empty'),
})

export const MeetingDeleteResponseSchema = z.object({ ok: z.literal(true) })

export type MeetingDeleteRequest = z.infer<typeof MeetingDeleteRequestSchema>
export type MeetingDeleteResponse = z.infer<typeof MeetingDeleteResponseSchema>

// ---------------------------------------------------------------------------
// model:status — check whether the local ASR model is already downloaded
// (item 0024)
// ---------------------------------------------------------------------------

export const ModelStatusRequestSchema = z.object({ modelId: z.string().min(1) })
export const ModelStatusResponseSchema = z.object({
  modelId: z.string(),
  downloaded: z.boolean(),
  sizeBytes: z.number(),
})

export type ModelStatusRequest = z.infer<typeof ModelStatusRequestSchema>
export type ModelStatusResponse = z.infer<typeof ModelStatusResponseSchema>

// ---------------------------------------------------------------------------
// model:download — start a download; progress is pushed as model:progress
// (item 0024)
// ---------------------------------------------------------------------------

export const ModelDownloadRequestSchema = z.object({ modelId: z.string().min(1) })
export const ModelDownloadResponseSchema = z.object({ ok: z.literal(true) })

export type ModelDownloadRequest = z.infer<typeof ModelDownloadRequestSchema>
export type ModelDownloadResponse = z.infer<typeof ModelDownloadResponseSchema>

// ---------------------------------------------------------------------------
// model:progress — main → renderer push event (item 0024)
//
// Emitted during a model download. `done: true` signals completion.
// `error` is set when the download failed.
// ---------------------------------------------------------------------------

export interface ModelProgressEvent {
  modelId: string
  bytesReceived: number
  bytesTotal: number
  done: boolean
  error?: string
}

// ---------------------------------------------------------------------------
// import:start — create an imported meeting and begin offline transcription
// (item 0026)
//
// Main generates the meeting id, persists the meeting (state 'live', source
// 'import'), builds the ASR provider, and starts draining spans. The renderer
// then streams decoded PCM frames via the import:frame one-way channel.
// ---------------------------------------------------------------------------

export const ImportStartRequestSchema = z.object({
  title: z.string().min(1, 'Meeting title cannot be empty'),
  primaryLanguage: z.string().min(1, 'Primary language cannot be empty'),
  /** Agenda items the user typed; empty when inferring. */
  agendaItems: z.array(z.object({ title: z.string().min(1), topic: z.string().min(1) })),
  /** Participants the user typed; empty when inferring. */
  participants: z.array(z.object({ name: z.string().min(1) })),
  /** When true, infer agenda + participants from the transcript before the final pass. */
  inferContext: z.boolean(),
})

export const ImportStartResponseSchema = z.object({
  /** The id of the newly created imported meeting. */
  meetingId: z.string().min(1),
})

export type ImportStartRequest = z.infer<typeof ImportStartRequestSchema>
export type ImportStartResponse = z.infer<typeof ImportStartResponseSchema>

// ---------------------------------------------------------------------------
// import:finish — signal end-of-file: stop transcription, infer (if asked),
// run the final pass, and mark the meeting Ended (item 0026)
// ---------------------------------------------------------------------------

export const ImportFinishRequestSchema = z.object({
  meetingId: z.string().min(1, 'Meeting ID cannot be empty'),
})

export const ImportFinishResponseSchema = z.object({
  meetingId: z.string().min(1),
})

export type ImportFinishRequest = z.infer<typeof ImportFinishRequestSchema>
export type ImportFinishResponse = z.infer<typeof ImportFinishResponseSchema>

// ---------------------------------------------------------------------------
// import:progress — main → renderer push event (item 0026)
//
// Coarse stage transitions for the import pipeline. The renderer owns the
// decode/stream percentage; main emits these stage changes. Validated
// renderer-side per principle #8.
// ---------------------------------------------------------------------------

export const ImportProgressEventSchema = z.object({
  stage: z.enum(['transcribing', 'inferring', 'extracting', 'done', 'error']),
  /** Optional 0–100 progress hint for the current stage. */
  percent: z.number().optional(),
  /** Set when stage is 'error'. */
  error: z.string().optional(),
})

export type ImportProgressEvent = z.infer<typeof ImportProgressEventSchema>

// ---------------------------------------------------------------------------
// context:inferFromText — structure a pasted agenda into title + agenda items
// + participants (paste-an-agenda, ADR 0029)
//
// The user pastes free text in Draft; main builds the extraction provider and
// calls inferContext({ source: { text } }). The resulting items fill the
// editable Draft fields as Confirmed items (pasting is an input method, not
// agent inference). Degrades to an empty context when no extraction provider is
// configured, so manual entry still works.
// ---------------------------------------------------------------------------

export const ContextInferFromTextRequestSchema = z.object({
  /** The raw text the user pasted (an agenda from Word/Markdown/anything). */
  text: z.string().min(1, 'Text cannot be empty'),
  /** The primary language for inference (e.g. 'nl', 'en'). */
  primaryLanguage: z.string().min(1, 'Primary language cannot be empty'),
})

export const ContextInferFromTextResponseSchema = InferredContextSchema

export type ContextInferFromTextRequest = z.infer<typeof ContextInferFromTextRequestSchema>
export type ContextInferFromTextResponse = z.infer<typeof ContextInferFromTextResponseSchema>

// ---------------------------------------------------------------------------
// agenda:changed — main → renderer push event (live agenda inference, ADR 0029)
//
// Emitted whenever the live agenda set changes (the slow agenda scheduler
// proposes new items). Carries the full current agenda (Confirmed + Proposed)
// so the renderer replaces its local agenda state, exactly like nudges:changed.
// ---------------------------------------------------------------------------

export const AgendaChangedPayloadSchema = z.object({
  agendaItems: z.array(AgendaItemSchema),
})

export type AgendaChangedPayload = z.infer<typeof AgendaChangedPayloadSchema>

// ---------------------------------------------------------------------------
// agendaItem:confirm — note-taker confirms a Proposed Agenda Item (ADR 0029)
//
// Persists state → 'confirmed' so the item becomes a live routing bucket
// immediately. Returns the updated item.
// ---------------------------------------------------------------------------

export const AgendaItemConfirmRequestSchema = z.object({
  agendaItemId: z.string().min(1, 'Agenda item ID cannot be empty'),
})

export const AgendaItemConfirmResponseSchema = AgendaItemSchema

export type AgendaItemConfirmRequest = z.infer<typeof AgendaItemConfirmRequestSchema>
export type AgendaItemConfirmResponse = z.infer<typeof AgendaItemConfirmResponseSchema>

// ---------------------------------------------------------------------------
// agendaItem:editAndConfirm — edit a Proposed Agenda Item's title/topic and
// confirm it in one step (ADR 0029)
// ---------------------------------------------------------------------------

export const AgendaItemEditAndConfirmRequestSchema = z.object({
  agendaItemId: z.string().min(1, 'Agenda item ID cannot be empty'),
  title: z.string().min(1, 'Agenda item title cannot be empty'),
  topic: z.string().min(1, 'Agenda item topic cannot be empty'),
})

export const AgendaItemEditAndConfirmResponseSchema = AgendaItemSchema

export type AgendaItemEditAndConfirmRequest = z.infer<typeof AgendaItemEditAndConfirmRequestSchema>
export type AgendaItemEditAndConfirmResponse = z.infer<
  typeof AgendaItemEditAndConfirmResponseSchema
>

// ---------------------------------------------------------------------------
// meeting:pause / meeting:resume — pause is a sub-state within Live (the same
// transcript continues after resume). Halts the live cadence (runtime.pause).
// ---------------------------------------------------------------------------

export const MeetingPauseRequestSchema = z.object({
  meetingId: z.string().min(1, 'Meeting ID cannot be empty'),
})
export const MeetingPauseResponseSchema = MeetingSchema

export type MeetingPauseRequest = z.infer<typeof MeetingPauseRequestSchema>
export type MeetingPauseResponse = z.infer<typeof MeetingPauseResponseSchema>

export const MeetingResumeRequestSchema = z.object({
  meetingId: z.string().min(1, 'Meeting ID cannot be empty'),
})
export const MeetingResumeResponseSchema = MeetingSchema

export type MeetingResumeRequest = z.infer<typeof MeetingResumeRequestSchema>
export type MeetingResumeResponse = z.infer<typeof MeetingResumeResponseSchema>

// ---------------------------------------------------------------------------
// Channel registry — exhaustive union of all channel names
// ---------------------------------------------------------------------------

export type IpcChannel =
  | 'ping'
  | 'settings:get'
  | 'settings:set'
  | 'egress:state'
  | 'secret:set'
  | 'secret:has'
  | 'provider:testConnection'
  | 'meeting:create'
  | 'agendaItem:add'
  | 'agendaItem:remove'
  | 'participant:add'
  | 'participant:remove'
  | 'meeting:start'
  | 'meeting:end'
  | 'audio:start'
  | 'audio:stop'
  | 'item:confirm'
  | 'item:editAndConfirm'
  | 'item:dismiss'
  | 'item:createConfirmed'
  | 'summary:query'
  | 'export:markdown'
  | 'export:copyMarkdown'
  | 'transcript:copy'
  | 'meeting:list'
  | 'meeting:load'
  | 'meeting:delete'
  | 'model:status'
  | 'model:download'
  | 'import:start'
  | 'import:finish'
  | 'context:inferFromText'
  | 'agendaItem:confirm'
  | 'agendaItem:editAndConfirm'
  | 'meeting:pause'
  | 'meeting:resume'

/**
 * One-way channels: renderer sends, main receives (no invoke/response).
 * These are registered via ipcMain.on, not ipcMain.handle.
 */
export type IpcOnewayChannel = 'audio:frame' | 'import:frame'

// ---------------------------------------------------------------------------
// Typed preload API surface exposed to the renderer via contextBridge
// ---------------------------------------------------------------------------

/** Cleanup function returned by onTranscriptSpan; call to remove the listener. */
export type UnsubscribeFn = () => void

export interface RendererApi {
  /** Send a ping to main; resolves with { pong: true }. */
  ping: () => Promise<PingResponse>
  /** Retrieve the current persisted settings. */
  settingsGet: () => Promise<SettingsGetResponse>
  /** Persist new settings. Replaces the full settings object. */
  settingsSet: (settings: SettingsSetRequest) => Promise<SettingsSetResponse>
  /** Get the current egress state derived from settings. */
  egressState: () => Promise<EgressState>
  /** Create a new meeting in draft state. */
  meetingCreate: (req: MeetingCreateRequest) => Promise<MeetingCreateResponse>
  /** Add an agenda item to a meeting. */
  agendaItemAdd: (req: AgendaItemAddRequest) => Promise<AgendaItemAddResponse>
  /** Remove an agenda item. */
  agendaItemRemove: (req: AgendaItemRemoveRequest) => Promise<AgendaItemRemoveResponse>
  /** Add a participant to a meeting. */
  participantAdd: (req: ParticipantAddRequest) => Promise<ParticipantAddResponse>
  /** Remove a participant. */
  participantRemove: (req: ParticipantRemoveRequest) => Promise<ParticipantRemoveResponse>
  /** Start a meeting (Draft → Live). */
  meetingStart: (req: MeetingStartRequest) => Promise<MeetingStartResponse>
  /**
   * Write an API key into safeStorage. The key value is transmitted to main
   * exactly once during entry and is never returned to the renderer.
   * (item 0016)
   */
  secretSet: (req: SecretSetRequest) => Promise<SecretSetResponse>
  /**
   * Check whether an API key is stored for the given name.
   * Returns a boolean presence flag — never the key value.
   * (item 0016)
   */
  secretHas: (req: SecretHasRequest) => Promise<SecretHasResponse>
  /**
   * Probe the configured provider's credentials with one cheap round-trip (5.1).
   * Surfaces auth/URL errors at config time. Never returns or logs the key.
   */
  providerTestConnection: (
    req: ProviderTestConnectionRequest,
  ) => Promise<ProviderTestConnectionResponse>
  /**
   * Tell main to open an ASR session. Call before sending audio frames.
   * (item 0015)
   */
  audioStart: (req: AudioStartRequest) => Promise<AudioStartResponse>
  /**
   * Tell main to close the active ASR session.
   * (item 0015)
   */
  audioStop: () => Promise<AudioStopResponse>
  /**
   * Send a raw PCM audio frame (Int16 LE, Uint8Array) to main.
   * Fire-and-forget: no response. Uses ipcRenderer.send, not invoke.
   * (item 0015)
   */
  audioSendFrame: (frame: Uint8Array) => void
  /**
   * Subscribe to transcript spans pushed from main.
   * Returns an unsubscribe function.
   * (item 0015)
   */
  onTranscriptSpan: (cb: (span: import('./domain/types').TranscriptSpan) => void) => UnsubscribeFn
  /**
   * Subscribe to proposed-item updates pushed from main.
   * Fired after every rolling extraction turn or final pass that produces ≥1
   * proposed Decision or Action. The callback receives the newly proposed items
   * for that turn; the UI merges/replaces its local proposed-item state.
   * Returns an unsubscribe function.
   * (item 0018)
   */
  onItemsChanged: (cb: (payload: ItemsChangedPayload) => void) => UnsubscribeFn
  /**
   * Subscribe to Discussion Summary events pushed from main.
   * Fired exactly once, after the final extraction pass completes (meeting end).
   * Returns an unsubscribe function.
   * (item 0018)
   */
  onItemsSummaries: (cb: (payload: ItemsSummariesPayload) => void) => UnsubscribeFn
  /**
   * Subscribe to nudge updates pushed from main (item 0019).
   * Fired after every extraction turn that may change the nudge set.
   * The callback receives the full derived nudge array; the UI replaces
   * its local nudge state.
   * Returns an unsubscribe function.
   */
  onNudgesChanged: (cb: (payload: NudgesChangedPayload) => void) => UnsubscribeFn
  /**
   * Confirm a Proposed Decision or Action (item 0018).
   * Transitions the item to Confirmed state.
   */
  itemConfirm: (req: ItemConfirmRequest) => Promise<ItemConfirmResponse>
  /**
   * Edit and confirm a Decision or Action in one step (item 0018).
   */
  itemEditAndConfirm: (req: ItemEditAndConfirmRequest) => Promise<ItemEditAndConfirmResponse>
  /**
   * Dismiss a Proposed Decision or Action (item 0018).
   * Removes the item; the agent may re-propose it if context changes.
   */
  itemDismiss: (req: ItemDismissRequest) => Promise<ItemDismissResponse>
  /**
   * Manually create a Confirmed Decision or Action during Live (item 0018).
   * Bypasses the Proposed state; the item is immediately Confirmed.
   */
  itemCreateConfirmed: (req: ItemCreateConfirmedRequest) => Promise<ItemCreateConfirmedResponse>
  /**
   * Subscribe to running summary updates pushed from main (item 0020).
   * Fired after each extraction cadence tick when summarise() produces a result.
   * The callback receives the full current running summary string; the UI
   * replaces its local summary text on each event.
   * Returns an unsubscribe function.
   */
  onSummaryChanged: (cb: (payload: SummaryChangedPayload) => void) => UnsubscribeFn
  /**
   * Ask a free-form question grounded in the current transcript (item 0020).
   * Main calls provider.query() and returns a plain-text answer.
   * Returns { answer: '' } if the provider has no query capability.
   */
  summaryQuery: (req: SummaryQueryRequest) => Promise<SummaryQueryResponse>
  /**
   * End the active meeting. Triggers the final extraction pass (Discussion
   * Summaries, final decisions/actions) and stops the runtime (item 0021).
   */
  meetingEnd: (req: MeetingEndRequest) => Promise<MeetingEndResponse>
  /**
   * Save meeting notes as a Markdown file. Main shows a save dialog.
   * Returns ok=false with a reason if the dialog was cancelled or the write failed.
   * (item 0022)
   */
  exportMarkdown: (req: ExportMarkdownRequest) => Promise<ExportMarkdownResponse>
  /**
   * Copy meeting notes as Markdown to the clipboard.
   * (item 0022)
   */
  exportCopyMarkdown: (req: ExportCopyMarkdownRequest) => Promise<ExportCopyMarkdownResponse>
  /**
   * Copy the full transcript of a meeting to the clipboard (item 0026).
   * Main serialises the persisted spans; only the meeting id is sent.
   */
  transcriptCopy: (req: TranscriptCopyRequest) => Promise<TranscriptCopyResponse>
  /**
   * List all meetings ordered newest-first (item 0023).
   * Used by the Home screen to show past meetings.
   */
  meetingList: (req: MeetingListRequest) => Promise<MeetingListResponse>
  /**
   * Load full state of a past meeting (item 0023).
   * Returns the meeting + all decisions, actions, agenda items, participants,
   * and discussion summaries so the Review screen can render a reopened meeting.
   */
  meetingLoad: (req: MeetingLoadRequest) => Promise<MeetingLoadResponse>
  /**
   * Permanently delete a meeting and all its data (item 0026).
   * Used by the Home screen to remove meetings from the overview.
   */
  meetingDelete: (req: MeetingDeleteRequest) => Promise<MeetingDeleteResponse>
  /**
   * Check whether the local ASR model is already downloaded (item 0024).
   * Returns { downloaded: true, sizeBytes } if present; { downloaded: false, sizeBytes: 0 } otherwise.
   */
  modelStatus: (req: ModelStatusRequest) => Promise<ModelStatusResponse>
  /**
   * Start downloading the local ASR model (item 0024).
   * Returns ok immediately; progress is pushed via onModelProgress events.
   */
  modelDownload: (req: ModelDownloadRequest) => Promise<ModelDownloadResponse>
  /**
   * Subscribe to model download progress events pushed from main (item 0024).
   * Fired during a model:download. done=true signals completion; error is set on failure.
   * Returns an unsubscribe function.
   */
  onModelProgress: (cb: (evt: ModelProgressEvent) => void) => UnsubscribeFn
  /**
   * Start an audio-file import (item 0026). Main creates the meeting and begins
   * offline transcription; the renderer then streams decoded PCM frames via
   * importSendFrame and calls importFinish at end-of-file. Returns the new
   * meeting id.
   */
  importStart: (req: ImportStartRequest) => Promise<ImportStartResponse>
  /**
   * Send a decoded PCM frame (Int16 LE, Uint8Array) for the active import
   * (item 0026). Fire-and-forget: no response. Uses ipcRenderer.send.
   */
  importSendFrame: (frame: Uint8Array) => void
  /**
   * Signal end-of-file for the active import (item 0026). Main stops
   * transcription, optionally infers context, runs the final pass, and marks the
   * meeting Ended. Returns the meeting id so the renderer can open it in Review.
   */
  importFinish: (req: ImportFinishRequest) => Promise<ImportFinishResponse>
  /**
   * Subscribe to import progress events pushed from main (item 0026).
   * Reports coarse stage transitions; stage 'done' signals completion and
   * 'error' carries a reason. Returns an unsubscribe function.
   */
  onImportProgress: (cb: (evt: ImportProgressEvent) => void) => UnsubscribeFn
  /**
   * Structure a pasted agenda into title + agenda items + participants
   * (paste-an-agenda, ADR 0029). Main calls inferContext over the text; the
   * Draft fields fill with the result as Confirmed items. Returns an empty
   * context when no extraction provider is configured.
   */
  inferContextFromText: (req: ContextInferFromTextRequest) => Promise<ContextInferFromTextResponse>
  /**
   * Subscribe to live agenda updates pushed from main (ADR 0029). Fired when the
   * slow agenda scheduler proposes new items. The callback receives the full
   * current agenda; the UI replaces its local agenda state. Returns an
   * unsubscribe function.
   */
  onAgendaChanged: (cb: (payload: AgendaChangedPayload) => void) => UnsubscribeFn
  /**
   * Confirm a Proposed Agenda Item (ADR 0029). Persists state → 'confirmed' so
   * it becomes a live routing bucket immediately. Returns the updated item.
   */
  agendaItemConfirm: (req: AgendaItemConfirmRequest) => Promise<AgendaItemConfirmResponse>
  /**
   * Edit a Proposed Agenda Item's title/topic and confirm it in one step
   * (ADR 0029).
   */
  agendaItemEditAndConfirm: (
    req: AgendaItemEditAndConfirmRequest,
  ) => Promise<AgendaItemEditAndConfirmResponse>
  /** Pause a Live meeting (sub-state within Live; halts the live cadence). */
  meetingPause: (req: MeetingPauseRequest) => Promise<MeetingPauseResponse>
  /** Resume a paused Live meeting; the same transcript continues. */
  meetingResume: (req: MeetingResumeRequest) => Promise<MeetingResumeResponse>
}
