/**
 * Draft-prep IPC handlers (audit A2b): meeting:create, agendaItem:add/remove/
 * confirm/editAndConfirm, participant:add/remove. Owns the PrepDeps repos.
 * Persisting the prepared agenda + participants against the real meeting is what
 * makes rolling-extraction routing and meeting:load work (audit C1).
 */

import { randomUUID } from 'crypto'

import {
  MeetingCreateRequestSchema,
  MeetingCreateResponseSchema,
  AgendaItemAddRequestSchema,
  AgendaItemAddResponseSchema,
  AgendaItemRemoveRequestSchema,
  AgendaItemRemoveResponseSchema,
  ParticipantAddRequestSchema,
  ParticipantAddResponseSchema,
  ParticipantRemoveRequestSchema,
  ParticipantRemoveResponseSchema,
  AgendaItemConfirmRequestSchema,
  AgendaItemConfirmResponseSchema,
  AgendaItemEditAndConfirmRequestSchema,
  AgendaItemEditAndConfirmResponseSchema,
} from '@shared/ipc'
import type {
  IpcChannel,
  MeetingCreateResponse,
  AgendaItemAddResponse,
  AgendaItemRemoveResponse,
  ParticipantAddResponse,
  ParticipantRemoveResponse,
  AgendaItemConfirmResponse,
  AgendaItemEditAndConfirmResponse,
} from '@shared/ipc'
import type { Clock } from '@shared/providers'

import type { agendaItemRepo } from '../db/repos/agendaItemRepo'
import type { meetingRepo } from '../db/repos/meetingRepo'
import type { participantRepo } from '../db/repos/participantRepo'

import type { Handler } from './handlerTypes'

/**
 * Draft-prep repos backing meeting:create, agendaItem:* and participant:*.
 * Members stay individually optional so a caller that only prepares an agenda
 * (or only persists the meeting row) degrades exactly as before (audit C1).
 */
export interface PrepDeps {
  meetingRepo?: ReturnType<typeof meetingRepo>
  agendaItemRepo?: ReturnType<typeof agendaItemRepo>
  participantRepo?: ReturnType<typeof participantRepo>
}

export interface PrepHandlerDeps {
  prep?: PrepDeps
  /** Clock for generating timestamps (meeting:create). */
  clock?: Clock
}

export function createPrepHandlers(deps: PrepHandlerDeps): Partial<Record<IpcChannel, Handler>> {
  return {
    'meeting:create': (raw: unknown): MeetingCreateResponse => {
      const req = MeetingCreateRequestSchema.parse(raw)

      const now = new Date(deps.clock?.now() ?? Date.now()).toISOString()
      const meeting: MeetingCreateResponse = {
        id: randomUUID(),
        title: req.title,
        state: 'draft',
        source: 'live',
        paused: false,
        createdAt: now,
        primaryLanguage: req.primaryLanguage,
        titleAutoGenerated: req.titleAutoGenerated,
      }

      // Persist the row so the Draft title + quick-start flag reach the DB and the
      // LiveSessionController preserves them (instead of its "Active Meeting"
      // fallback). Optional dep keeps the registry unit-testable without a DB.
      deps.prep?.meetingRepo?.insert(meeting)

      return MeetingCreateResponseSchema.parse(meeting)
    },
    'agendaItem:add': (raw: unknown): AgendaItemAddResponse => {
      const req = AgendaItemAddRequestSchema.parse(raw)

      const agendaItem: AgendaItemAddResponse = {
        id: randomUUID(),
        title: req.title,
        topic: req.topic,
        state: 'confirmed',
      }

      // Persist against the real meeting so rolling-extraction routing sees the
      // agenda and meeting:load restores it (audit C1). Optional dep keeps the
      // registry unit-testable without a DB.
      deps.prep?.agendaItemRepo?.insert(agendaItem, req.meetingId)

      return AgendaItemAddResponseSchema.parse(agendaItem)
    },
    'agendaItem:remove': (raw: unknown): AgendaItemRemoveResponse => {
      const req = AgendaItemRemoveRequestSchema.parse(raw)
      deps.prep?.agendaItemRepo?.delete(req.agendaItemId)
      return AgendaItemRemoveResponseSchema.parse({ ok: true })
    },
    'participant:add': (raw: unknown): ParticipantAddResponse => {
      const req = ParticipantAddRequestSchema.parse(raw)

      const participant: ParticipantAddResponse = {
        id: randomUUID(),
        name: req.name,
      }

      // Persist against the real meeting so owner assignment has a participant list
      // and meeting:load restores it (audit C1).
      deps.prep?.participantRepo?.insert(participant, req.meetingId)

      return ParticipantAddResponseSchema.parse(participant)
    },
    'participant:remove': (raw: unknown): ParticipantRemoveResponse => {
      const req = ParticipantRemoveRequestSchema.parse(raw)
      deps.prep?.participantRepo?.delete(req.participantId)
      return ParticipantRemoveResponseSchema.parse({ ok: true })
    },
    'agendaItem:confirm': (raw: unknown): AgendaItemConfirmResponse => {
      const req = AgendaItemConfirmRequestSchema.parse(raw)
      const repo = deps.prep?.agendaItemRepo
      if (repo === undefined) {
        throw new Error('agendaItem:confirm is not available')
      }
      const item = repo.findById(req.agendaItemId)
      if (item === null) {
        throw new Error('agendaItem:confirm: item not found')
      }
      const confirmed = { ...item, state: 'confirmed' as const }
      repo.update(confirmed)
      return AgendaItemConfirmResponseSchema.parse(confirmed)
    },
    'agendaItem:editAndConfirm': (raw: unknown): AgendaItemEditAndConfirmResponse => {
      const req = AgendaItemEditAndConfirmRequestSchema.parse(raw)
      const repo = deps.prep?.agendaItemRepo
      if (repo === undefined) {
        throw new Error('agendaItem:editAndConfirm is not available')
      }
      const item = repo.findById(req.agendaItemId)
      if (item === null) {
        throw new Error('agendaItem:editAndConfirm: item not found')
      }
      const updated = { ...item, title: req.title, topic: req.topic, state: 'confirmed' as const }
      repo.update(updated)
      return AgendaItemEditAndConfirmResponseSchema.parse(updated)
    },
  }
}
